// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminAuditResult } from "./AdminAuditResult";

/**
 * One row of `microapp_admin_audit`. Stable wire shape — every
 * field is present in the JSON payload returned by
 * `nexo/admin/microapp_audit/tail`.
 */
export type AdminAuditRow = { 
/**
 * Microapp identity (extension id from `extensions.yaml`).
 */
microapp_id: string, 
/**
 * Full JSON-RPC method (`nexo/admin/<domain>/<method>`).
 */
method: string, 
/**
 * Required capability (e.g. `agents_crud`). When the call
 * was denied, this is the capability that was missing.
 */
capability: string, 
/**
 * SHA-256 of canonicalised params (sorted keys). Lets
 * operators detect repeated identical calls without storing
 * PII payloads.
 */
args_hash: string, 
/**
 * Epoch milliseconds when dispatch started.
 */
started_at_ms: bigint, 
/**
 * `"ok"` | `"error"` | `"denied"`.
 */
result: AdminAuditResult, 
/**
 * Wall-clock duration of the dispatch.
 */
duration_ms: bigint, 
/**
 * Phase 83.8.12.7 — tenant scope for the call. Sniffed from
 * `params.tenant_id` (string) when present; legacy rows /
 * non-tenant-scoped calls (echo, pairing, credentials)
 * leave it `null`.
 */
tenant_id?: string | null, };
