// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Outcome of an admin RPC dispatch — written to the audit table
 * alongside every call.
 */
export type AdminAuditResult = "ok" | "error" | "denied";
