// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EscalationReason } from "./EscalationReason";
import type { EscalationUrgency } from "./EscalationUrgency";
import type { ProcessingControlState } from "./ProcessingControlState";
import type { ProcessingScope } from "./ProcessingScope";
import type { ResolvedBy } from "./ResolvedBy";
import type { TranscriptRole } from "./TranscriptRole";

/**
 * Discriminated event variant. v0 only emits
 * `TranscriptAppended`. Other slots are reserved enum entries
 * surfaced when the corresponding agent kind ships.
 */
export type AgentEventKind = { "kind": "transcript_appended", 
/**
 * Owning agent.
 */
agent_id: string, 
/**
 * Conversation scope.
 */
session_id: string, 
/**
 * Monotonic sequence within `session_id` — equal to the
 * 0-based index of the entry in the session's JSONL.
 */
seq: bigint, 
/**
 * Speaker role.
 */
role: TranscriptRole, 
/**
 * Redacted body (PII replaced with `[REDACTED:label]`).
 */
body: string, 
/**
 * Epoch milliseconds when the entry was recorded.
 */
sent_at_ms: bigint, 
/**
 * Opaque external sender id when applicable (channel
 * user id, peer agent id, …).
 */
sender_id?: string | null, 
/**
 * Channel/plugin that produced or received the entry
 * (e.g. `whatsapp`, `telegram`, `internal`).
 */
source_plugin: string, 
/**
 * Phase 83.8.12 — owning tenant. `None` for agents
 * predating multi-tenant. Firehose subscribers filter
 * on this without re-querying agents.yaml.
 */
tenant_id?: string | null, } | { "kind": "pending_inbounds_dropped", 
/**
 * Owning agent.
 */
agent_id: string, 
/**
 * Scope under which the drop happened. Carried whole
 * (rather than just `(channel, account_id, contact_id)`)
 * so future scope variants stay forward-compatible.
 */
scope: ProcessingScope, 
/**
 * Number of pending inbounds evicted by THIS push.
 */
dropped: number, 
/**
 * Epoch ms when the eviction happened.
 */
at_ms: bigint, } | { "kind": "escalation_requested", 
/**
 * Owning agent.
 */
agent_id: string, 
/**
 * Scope of the work item the agent is escalating.
 */
scope: ProcessingScope, 
/**
 * Free-form summary the agent supplied (already capped
 * to 500 chars by the admin handler before emit).
 */
summary: string, 
/**
 * Closed-enum reason for the escalation.
 */
reason: EscalationReason, 
/**
 * Operator hint on how aggressively to surface.
 */
urgency: EscalationUrgency, 
/**
 * Epoch ms when the agent raised the request.
 */
requested_at_ms: bigint, 
/**
 * Phase 83.8.12 — owning tenant; `None` for legacy /
 * single-tenant deployments. Firehose subscribers route
 * per-tenant without re-querying `agents.yaml`.
 */
tenant_id?: string | null, } | { "kind": "escalation_resolved", 
/**
 * Owning agent.
 */
agent_id: string, 
/**
 * Scope that was settled. Same value the `Pending`
 * emit carried.
 */
scope: ProcessingScope, 
/**
 * Epoch ms when the resolution happened.
 */
resolved_at_ms: bigint, 
/**
 * How the escalation was settled.
 */
by: ResolvedBy, 
/**
 * Phase 83.8.12 — owning tenant. Mirrors the
 * `Requested` shape so the pair stays
 * shape-symmetrical.
 */
tenant_id?: string | null, } | { "kind": "processing_state_changed", 
/**
 * Owning agent (denormalised from `scope` so subscribers
 * filter without parsing the discriminator).
 */
agent_id: string, 
/**
 * Scope whose state flipped.
 */
scope: ProcessingScope, 
/**
 * State observed immediately before the transition.
 */
prev_state: ProcessingControlState, 
/**
 * State the handler installed.
 */
new_state: ProcessingControlState, 
/**
 * Epoch ms when the transition happened.
 */
at_ms: bigint, 
/**
 * Phase 83.8.12 — owning tenant. `None` for legacy /
 * single-tenant deployments.
 */
tenant_id?: string | null, } | { "kind": "security_event", } & ({ "security_kind": "token_rotated", 
/**
 * Epoch milliseconds when the rotation persisted.
 */
at_ms: bigint, 
/**
 * Previous operator-token-hash (16-char sha256-hex
 * prefix). Zeroed (`""`) for the very first rotation
 * after boot when no prior hash is in cache.
 */
prev_hash: string, 
/**
 * New operator-token-hash.
 */
new_hash: string, 
/**
 * Optional operator-supplied audit hint, capped to
 * `auth::REASON_MAX_LEN` chars by the handler.
 */
reason?: string | null, }) | { "kind": "peer_typing", 
/**
 * Channel that produced the presence signal
 * (e.g. `whatsapp`).
 */
channel: string, 
/**
 * Channel-instance qualifier (e.g. `smoketest`). Empty
 * when the channel does not support multi-instance.
 */
account_id: string, 
/**
 * Channel-native sender id (e.g.
 * `573154645370@s.whatsapp.net`).
 */
sender_id: string, 
/**
 * `true` = peer is currently typing (composing).
 * `false` = peer stopped typing (paused).
 */
composing: boolean, 
/**
 * Epoch ms when the plugin observed the presence change.
 */
at_ms: bigint, 
/**
 * Owning agent when the plugin can resolve which agent
 * the conversation belongs to (single-agent inbound
 * binding). `None` for multi-agent setups — operator
 * dashboards then match by `(channel, account_id,
 * sender_id)` against every conversation.
 */
agent_id?: string | null, 
/**
 * Phase 83.8.12 — owning tenant. `None` for legacy /
 * single-tenant deployments.
 */
tenant_id?: string | null, } | { "kind": "whatsapp_bot_message", 
/**
 * WhatsApp plugin instance label (`smoketest`,
 * `default`, …). Resolves to the paired account.
 */
instance: string, 
/**
 * Bot JID, e.g. `718584497008509@bot`.
 */
bot_jid: string, 
/**
 * This chunk's stanza id (different per chunk).
 */
msg_id: string, 
/**
 * The original outbound id we sent to the bot. Constant
 * across every chunk of one logical reply.
 */
target_id: string, 
/**
 * `first` / `inner` / `last`. `last` = reply complete.
 */
edit: string, 
/**
 * Concatenated `AIRichResponseMessage.submessages[].messageText`
 * for this snapshot.
 */
text: string, 
/**
 * Epoch ms when the daemon received the chunk.
 */
at_ms: bigint, };
