// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminAuditResult } from "./AdminAuditResult";

/**
 * Filter passed to `nexo/admin/microapp_audit/tail`. Every
 * field optional; combine to narrow the result set.
 */
export type AuditTailFilter = { 
/**
 * Restrict to a single microapp.
 */
microapp_id?: string | null, 
/**
 * Restrict to one JSON-RPC method.
 */
method?: string | null, 
/**
 * Restrict to one outcome.
 */
result?: AdminAuditResult | null, 
/**
 * Restrict to one tenant.
 */
tenant_id?: string | null, 
/**
 * Lower-bound timestamp (epoch ms). Use
 * `now - duration_ms` for human-friendly windows
 * ("last 24h", "last 7d", …).
 */
since_ms?: bigint | null, 
/**
 * Max rows to return. Server clamps to `[1, 500]`. `0` →
 * default 50.
 */
limit: number, 
/**
 * Pagination offset. `0` for the first page; subsequent
 * pages set this to the previous response's `next_offset`.
 */
offset: number, };
