// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminAuditRow } from "./AdminAuditRow";

/**
 * Paginated response for `nexo/admin/microapp_audit/tail`.
 * Frontend stores `entries`, appends on `loadMore` until
 * `has_more = false`.
 */
export type AuditTailPage = { 
/**
 * Rows in newest-first order, capped by `filter.limit`.
 */
entries: Array<AdminAuditRow>, 
/**
 * Total matching rows (without `limit`/`offset`). Useful
 * for "showing N of M" UI labels.
 */
total: bigint, 
/**
 * `true` when `entries.len()` was capped by `limit` and
 * more rows match the filter.
 */
has_more: boolean, 
/**
 * Offset to pass to the next call's `filter.offset`.
 * `None` when `has_more = false`.
 */
next_offset?: number | null, };
