// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventSourceMeta } from "./EventSourceMeta";

/**
 * Identifies which inbound binding a tool call originated from.
 *
 * Stamped on every tool call dispatched to a Phase 11 stdio
 * extension or a Phase 12 MCP server (under `params._meta.nexo.binding`).
 * A microapp reads it to route work to the correct tenant /
 * channel / account.
 *
 * `binding_id` is rendered as `<channel>:<account_id|"default">`
 * — a stable identifier that survives `agents.yaml` reloads
 * (does NOT depend on the binding vector index).
 *
 * `mcp_channel_source` is populated when the inbound that
 * triggered the call arrived via a Phase 80.9 MCP channel
 * server (`"slack"`, `"telegram"`, etc.), allowing a tool to
 * distinguish "telegram-binding answered via MCP slack server"
 * from "telegram-binding answered via the native Telegram
 * plugin" while still seeing the same `(channel, account_id)`
 * tuple.
 *
 * # Example
 *
 * ```
 * use nexo_tool_meta::BindingContext;
 *
 * let ctx = BindingContext::agent_only("ana");
 * assert_eq!(ctx.agent_id, "ana");
 * assert!(ctx.channel.is_none());
 * ```
 */
export type BindingContext = { 
/**
 * Stable agent identifier (`agents.yaml.<id>`).
 */
agent_id: string, 
/**
 * Active session UUID. `None` outside an LLM turn (heartbeat
 * bootstrap, delegation receive, tests).
 */
session_id: string | null, 
/**
 * Channel name as declared in `InboundBinding.plugin`
 * (`"whatsapp"`, `"telegram"`, `"email"`, `"web"`, …).
 * `None` for contexts without a binding match.
 */
channel: string | null, 
/**
 * Account / instance discriminator from
 * `InboundBinding.instance`. `None` when the binding
 * declared no instance (single-account default).
 */
account_id: string | null, 
/**
 * Stable binding identifier rendered as
 * `<channel>:<account_id|"default">`. `None` for
 * bindingless contexts.
 */
binding_id: string | null, 
/**
 * Phase 80.9 — MCP channel server name when the inbound
 * arrived via `notifications/nexo/channel`. `None` for
 * native-channel inbounds. Examples: `"slack"`,
 * `"telegram"`, `"imessage"`.
 */
mcp_channel_source: string | null, 
/**
 * Phase 82.4 — event-subscriber metadata when the agent's
 * inbound was synthesised from a NATS event (subject pattern
 * match). `None` for human-message turns / native-channel
 * inbounds.
 */
event_source: EventSourceMeta | null, 
/**
 * Phase 83.8.12 — SaaS tenant (tenant) key. `None` for
 * agents that predate the multi-tenant model
 * (`agents.yaml.<id>` without an `tenant_id` field).
 * Multi-tenant filtering across admin RPC + microapp tools
 * keys on this field. Sits ABOVE `account_id`, which
 * remains the channel-side discriminator.
 */
tenant_id?: string | null, 
/**
 * Phase 81.19.b locale follow-up item 6 — resolved BCP-47
 * locale for this binding (`InboundBinding.language` over
 * `AgentConfig.language`). When present, the SDK's STT
 * inbound transform handler trims to ISO-639-1 and passes
 * it as a hint to whisper for accented audio. `None` lets
 * whisper auto-detect.
 */
language?: string | null, };
