// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Operator-facing escalation reason. Closed enum (no
 * `Other` slot — agents that can't classify use `Other`,
 * which is itself a value).
 */
export type EscalationReason = "out_of_scope" | "missing_data" | "needs_human_judgment" | "complaint" | "error" | "ambiguity" | "policy_violation" | "unknown_query" | "other";
