// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Operator-facing urgency hint. Default `Normal`.
 */
export type EscalationUrgency = "low" | "normal" | "high";
