// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Metadata describing the event that triggered an agent turn.
 *
 * Wire-shape struct — caller-built by the event-subscriber
 * runtime, caller-read by microapps and downstream tools.
 * Field additions are deliberate semver-major (the JSON wire
 * shape changes regardless), so this type is intentionally
 * **not** `#[non_exhaustive]`.
 */
export type EventSourceMeta = { 
/**
 * NATS subject that triggered the turn (e.g.
 * `"webhook.github_main.pull_request"`).
 */
subject: string, 
/**
 * Envelope id from the upstream event payload (when
 * available — webhook events carry one;
 * custom-published events may not).
 */
envelope_id: string | null, 
/**
 * Synthesis mode the binding was configured with —
 * `"synthesize"` or `"tick"`. Tools can branch behaviour
 * (e.g. fetch payload only when mode is `"tick"`).
 */
synthesis_mode: string, };
