// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 3-way discriminator for the origin of an agent turn.
 *
 * Mirrors the trichotomy used by inbound provenance tracking
 * (external_user / inter_session / internal_system) so microapps
 * can branch handlers on the message origin without re-deriving
 * it from sender_id presence alone.
 */
export type InboundKind = "external_user" | "internal_system" | "inter_session";
