// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InboundKind } from "./InboundKind";

/**
 * Per-turn metadata about the inbound message that triggered the
 * agent turn.
 *
 * Stamped on every tool call dispatched to a Phase 11 stdio
 * extension or a Phase 12 MCP server (under
 * `params._meta.nexo.inbound`). All fields except `kind` are
 * optional; consumers must tolerate absence and branch
 * gracefully.
 *
 * # Example — external user message
 *
 * ```
 * use nexo_tool_meta::{InboundKind, InboundMessageMeta};
 *
 * let meta = InboundMessageMeta::external_user("+5491100", "wa.ABCD1234");
 * assert_eq!(meta.kind, InboundKind::ExternalUser);
 * assert_eq!(meta.sender_id.as_deref(), Some("+5491100"));
 * assert_eq!(meta.msg_id.as_deref(), Some("wa.ABCD1234"));
 * ```
 *
 * # Example — internal system tick
 *
 * ```
 * use nexo_tool_meta::{InboundKind, InboundMessageMeta};
 *
 * let meta = InboundMessageMeta::internal_system();
 * assert_eq!(meta.kind, InboundKind::InternalSystem);
 * assert!(meta.sender_id.is_none());
 * assert!(meta.msg_id.is_none());
 * ```
 */
export type InboundMessageMeta = { 
/**
 * Origin discriminator. Always present when the bucket is.
 */
kind: InboundKind, 
/**
 * Provider-native sender id (E.164 phone, telegram_user_id,
 * RFC822 from-address, slack U-id, …). `None` for kinds
 * other than `ExternalUser` and for paths where the provider
 * does not expose a sender id (e.g. webhook with no auth).
 */
sender_id?: string | null, 
/**
 * Provider-native message id (single canonical, no shortened
 * alias). Used for idempotency, dedupe, and as the
 * `reply_to_msg_id` target on subsequent turns. When a
 * debounce window collapses several inbound messages into a
 * single turn, this carries the id of the **first** message
 * in the batch.
 */
msg_id?: string | null, 
/**
 * Inbound timestamp in UTC. Wire shape: RFC3339 string via
 * chrono's serde adapter. Producers must clamp wildly-skewed
 * provider timestamps to `now()` before emitting.
 */
inbound_ts?: string | null, 
/**
 * Provider-native id of the message this one replies to.
 * `None` when the inbound is not a reply.
 */
reply_to_msg_id?: string | null, 
/**
 * `true` when the inbound carries non-text media
 * (image/audio/video/file/sticker). Microapps gate
 * media-aware tools on this; the actual bytes/URLs live in
 * `arguments`, not in `_meta`.
 */
has_media?: boolean, 
/**
 * Origin session id when `kind == InterSession` (delegation
 * receive). `None` otherwise.
 */
origin_session_id?: string | null, };
