// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Full detail used by `mcp/get` + `mcp/upsert` payloads. Fields
 * not relevant to a given transport are `None` / empty.
 */
export type McpServerDetail = { 
/**
 * Stable identifier (key in `mcp.servers`).
 */
name: string, 
/**
 * Transport kind (`"stdio"` | `"streamable_http"` | `"sse"` | `"auto"`).
 */
transport: string, 
/**
 * Stdio transport — executable path / shell command.
 */
command?: string | null, 
/**
 * Stdio transport — argv tail.
 */
args?: Array<string>, 
/**
 * Stdio transport — env vars forwarded to the child.
 */
env?: { [key in string]: string }, 
/**
 * Stdio transport — working directory.
 */
cwd?: string | null, 
/**
 * HTTP / SSE / Auto transport — server URL.
 */
url?: string | null, 
/**
 * HTTP / SSE / Auto transport — extra headers.
 */
headers?: { [key in string]: string }, 
/**
 * All transports — log level override.
 */
log_level?: string | null, 
/**
 * All transports — per-server override of the global
 * `mcp.context.passthrough` flag.
 */
context_passthrough?: boolean | null, };
