// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Compact summary used by `mcp/list` responses.
 */
export type McpServerSummary = { 
/**
 * Stable identifier (key in `mcp.servers`).
 */
name: string, 
/**
 * Transport kind (`"stdio"` | `"streamable_http"` | `"sse"` | `"auto"`).
 */
transport: string, 
/**
 * Optional log level override (passed to the server via
 * `logging/setLevel` post-init when supported).
 */
log_level?: string | null, };
