// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpServerDetail } from "./McpServerDetail";

/**
 * Response for `nexo/admin/mcp/get`. `server: None` is the
 * not-found case (daemon does NOT return an error so callers
 * can probe for existence cheaply).
 */
export type McpServersGetResponse = { 
/**
 * Matching server, or `None` when the name is unknown.
 */
server: McpServerDetail | null, };
