// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Params for `nexo/admin/mcp/get`.
 */
export type McpServersGetParams = { 
/**
 * Server name to fetch.
 */
name: string, };
