// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpServerDetail } from "./McpServerDetail";

/**
 * Response for `nexo/admin/mcp/upsert`.
 */
export type McpServersUpsertResponse = { 
/**
 * Final server record after the write.
 */
server: McpServerDetail, 
/**
 * `true` when this call created a new server, `false` when
 * it updated an existing one (idempotent retry).
 */
created: boolean, };
