// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for `nexo/admin/mcp/delete`.
 */
export type McpServersDeleteResponse = { 
/**
 * `true` when the entry was removed, `false` when the name
 * had no record (idempotent retry safe).
 */
removed: boolean, };
