// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Params for `nexo/admin/mcp/delete`.
 */
export type McpServersDeleteParams = { 
/**
 * Server name to remove.
 */
name: string, };
