// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemoryEntryWire } from "./MemoryEntryWire";

/**
 * Response for `nexo/admin/memory/query`.
 */
export type MemoryQueryResponse = { 
/**
 * Matching entries newest-first within the relevance band.
 */
entries: Array<MemoryEntryWire>, };
