// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Params for `nexo/admin/memory/delete_snapshot`.
 */
export type MemorySnapshotsDeleteParams = { 
/**
 * Owning agent. Snapshots are partitioned by agent_id, so a
 * rogue id can't delete another agent's bundle.
 */
agent_id: string, 
/**
 * Tenant scope. Empty string = "default".
 */
tenant: string, 
/**
 * Snapshot id (UUID-shaped) to remove.
 */
id: string, };
