// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Params for `nexo/admin/memory/query`.
 */
export type MemoryQueryParams = { 
/**
 * Agent whose memory to search.
 */
agent_id: string, 
/**
 * Free-text query. Empty string returns the most recent
 * entries (recency wins when no query terms hit the FTS5
 * MATCH).
 */
query: string, 
/**
 * Max rows to return. Server-side clamp [1, 100], default 20.
 */
limit: number, };
