// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One memory entry over the wire. Mirrors
 * `nexo_memory::MemoryEntry` minus internal-only fields.
 */
export type MemoryEntryWire = { 
/**
 * Stable UUID (string for wire stability).
 */
id: string, 
/**
 * Owning agent.
 */
agent_id: string, 
/**
 * Memory body (markdown / plain text).
 */
content: string, 
/**
 * Operator-set tags (`#user`, `#feedback`, etc.).
 */
tags: Array<string>, 
/**
 * Auto-derived concept tags (Phase 10.7 derivation).
 */
concept_tags: Array<string>, 
/**
 * ISO-8601 UTC timestamp of memory creation.
 */
created_at: string, 
/**
 * Memory type (User / Feedback / Project / Reference) —
 * drives per-type half-life decay in scoring.
 */
memory_type?: string | null, };
