// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for `nexo/admin/memory/delete_snapshot`.
 */
export type MemorySnapshotsDeleteResponse = { 
/**
 * `true` when the bundle was removed; idempotent retry safe
 * (returns `true` on missing id too — daemon's local-fs
 * delete is `Ok(())` for already-gone bundles).
 */
removed: boolean, };
