// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SnapshotMetaWire } from "./SnapshotMetaWire";

/**
 * Response for `nexo/admin/memory/list_snapshots`.
 */
export type MemorySnapshotsListResponse = { 
/**
 * Snapshots ordered by `created_at_ms` descending (newest first).
 */
snapshots: Array<SnapshotMetaWire>, };
