// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Params for `nexo/admin/memory/list_snapshots`.
 */
export type MemorySnapshotsListParams = { 
/**
 * Agent whose snapshots to list.
 */
agent_id: string, 
/**
 * Tenant scope. Empty string = "default".
 */
tenant: string, };
