// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Kind discriminator. `#[non_exhaustive]` so future kinds
 * (e.g. `RateLimitTripped` once 83.16's respawn-throttle
 * follow-up ships) can land non-major.
 */
export type MicroappErrorKind = "init_timeout" | "handler_panic" | "exit" | "capability_denied";
