// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MicroappErrorKind } from "./MicroappErrorKind";

/**
 * Notification payload.
 */
export type MicroappError = { 
/**
 * Operator-facing extension id (`extensions.yaml.entries.<id>`).
 */
microapp_id: string, 
/**
 * Discriminator for the four canonical error categories.
 */
kind: MicroappErrorKind, 
/**
 * JSON-RPC `id` that triggered the error, when applicable.
 * `None` for `Exit` (no in-flight call) and for boot-time
 * failures.
 */
correlation_id?: string | null, 
/**
 * UTC wall-clock at which the daemon observed the error.
 */
occurred_at: string, 
/**
 * One-line human-readable summary surfaced in the admin-ui
 * hover tooltip and Prometheus annotations. Keep terse —
 * stack trace goes in `stack_trace`.
 */
summary: string, 
/**
 * Optional multi-line stack trace / traceback. Bounded by
 * the daemon's stdio reader (16 KiB cap by convention) so
 * a runaway microapp can't blow up the broker.
 */
stack_trace?: string | null, };
