// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Context the framework hands transformers + channel plugins for
 * every outbound reply. Read-only.
 */
export type OutboundReplyContext = { 
/**
 * Stable agent id producing the reply.
 */
agent_id: string, 
/**
 * Session UUID stringified.
 */
session_id: string, 
/**
 * `whatsapp` / `telegram` / `email` / etc.
 */
channel: string, 
/**
 * Plugin instance discriminator (e.g. `smoketest`,
 * `sucursal-norte`). `None` for single-instance channels.
 */
instance?: string | null, 
/**
 * Channel-native recipient address (whatsapp jid, telegram
 * chat_id, …). Optional because some pipelines (e.g. system-
 * injected ticks) don't have one yet.
 */
recipient?: string | null, 
/**
 * Tenant id when the agent is tenant-scoped, otherwise `None`.
 */
tenant_id?: string | null, 
/**
 * Conversation key used by operator UIs to group messages —
 * matches the one the firehose store + chat sidebar use
 * (`<agent_id>:session:<session_id>` for transcript-keyed
 * chats). Microapps key per-conversation state on this.
 */
conversation_key: string, 
/**
 * ISO-639-1 hint from `agents.yaml.<id>.language`. Lets reply
 * transformers localise their behaviour (e.g. voice_mode
 * picks a region-appropriate Edge voice when the operator
 * hasn't manually overridden it).
 */
language?: string | null, };
