// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Response for `nexo/admin/plugins/doctor`.
 */
export type PluginsDoctorResponse = { 
/**
 * Full `PluginDiscoveryReport` JSON. Identical to what the
 * `agent doctor plugins --json` CLI emits — a stable wire
 * shape since Phase 81.11 (`doctor_render::render_json`).
 */
report: JsonValue, 
/**
 * Server-side wall-clock when the report was built (ms
 * since epoch). Operators see this as a "as of …" hint.
 */
generated_at_ms: bigint, };
