// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProcessingScope } from "./ProcessingScope";

/**
 * Persisted control state for one scope. `AgentActive` is the
 * default — every scope starts in this state and the store
 * only allocates a row once an operator pauses it.
 */
export type ProcessingControlState = { "state": "agent_active" } | { "state": "paused_by_operator", 
/**
 * Echo of the scope so callers reading state alone
 * have the discriminator handy.
 */
scope: ProcessingScope, 
/**
 * Epoch ms when the pause was set.
 */
paused_at_ms: bigint, 
/**
 * `token_hash` of the operator's bearer (Phase 82.12
 * helper) so audits can correlate without storing the
 * cleartext token.
 */
operator_token_hash: string, 
/**
 * Free-form reason. Optional.
 */
reason?: string | null, };
