// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Scope the operator is suspending (or operating on).
 * `#[non_exhaustive]` so adding new agent shapes later is
 * non-breaking. v0 only routes `Conversation` end-to-end;
 * other variants are accepted on the wire but the dispatcher
 * returns `-32601 not_implemented`.
 */
export type ProcessingScope = { "kind": "conversation", 
/**
 * Owning agent.
 */
agent_id: string, 
/**
 * Channel plugin (e.g. `whatsapp`).
 */
channel: string, 
/**
 * Channel-side account id (e.g. WA business id).
 */
account_id: string, 
/**
 * Counterparty id (e.g. WA jid).
 */
contact_id: string, 
/**
 * Phase 80.9 — populated when the conversation
 * arrived via an MCP channel server (e.g. `slack`).
 * `None` for native-channel inbounds.
 */
mcp_channel_source?: string | null, } | { "kind": "agent_binding", 
/**
 * Owning agent.
 */
agent_id: string, 
/**
 * Channel plugin.
 */
channel: string, 
/**
 * Channel-side account id.
 */
account_id: string, } | { "kind": "agent", 
/**
 * Agent id.
 */
agent_id: string, } | { "kind": "event_stream", 
/**
 * Owning agent.
 */
agent_id: string, 
/**
 * Subject glob.
 */
subject_pattern: string, } | { "kind": "batch_queue", 
/**
 * Owning agent.
 */
agent_id: string, 
/**
 * Queue name.
 */
queue_name: string, } | { "kind": "custom", 
/**
 * Owning agent.
 */
agent_id: string, 
/**
 * Caller-defined scope discriminator.
 */
scope_kind: string, 
/**
 * Caller-defined scope id.
 */
scope_id: string, };
