// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a previously-pending escalation was settled.
 */
export type ResolvedBy = { "kind": "operator_takeover" } | { "kind": "operator_dismissed", 
/**
 * Free-form reason — kept for the audit log.
 */
reason: string, } | { "kind": "agent_resolved" };
