// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Phase 82.10.o — security-domain audit events. Nested under
 * [`AgentEventKind::SecurityEvent`] so subscribers persist
 * every variant alongside transcript / escalation events for
 * a unified audit log.
 */
export type SecurityEventKind = { "security_kind": "token_rotated", 
/**
 * Epoch milliseconds when the rotation persisted.
 */
at_ms: bigint, 
/**
 * Previous operator-token-hash (16-char sha256-hex
 * prefix). Zeroed (`""`) for the very first rotation
 * after boot when no prior hash is in cache.
 */
prev_hash: string, 
/**
 * New operator-token-hash.
 */
new_hash: string, 
/**
 * Optional operator-supplied audit hint, capped to
 * `auth::REASON_MAX_LEN` chars by the handler.
 */
reason?: string | null, };
