// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wire-side projection of `nexo_memory_snapshot::SnapshotMeta`.
 * Internal fields (bundle_path, schema_versions, git_oid)
 * surfaced as opaque strings for forward-compat.
 */
export type SnapshotMetaWire = { 
/**
 * Snapshot id (UUID-shaped string).
 */
id: string, 
/**
 * Owning agent.
 */
agent_id: string, 
/**
 * Tenant scope.
 */
tenant: string, 
/**
 * Optional human-readable label set at create time.
 */
label?: string | null, 
/**
 * Wall-clock millis since epoch when the bundle was written.
 */
created_at_ms: bigint, 
/**
 * Absolute filesystem path of the bundle archive.
 */
bundle_path: string, 
/**
 * Bundle size in bytes (after compression / encryption).
 */
bundle_size_bytes: bigint, 
/**
 * Hex-encoded SHA-256 of the bundle.
 */
bundle_sha256: string, 
/**
 * `Some(oid)` when git-mode snapshots captured a commit.
 */
git_oid?: string | null, 
/**
 * True when the bundle is age-encrypted (`*.tar.zst.age`).
 */
encrypted: boolean, 
/**
 * True when redaction policies stripped fields at capture time.
 */
redactions_applied: boolean, };
