// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Speaker role mirror — kept on the wire side so SDK types
 * don't pull in the core crate. Matches
 * `nexo_core::agent::transcripts::TranscriptRole`.
 */
export type TranscriptRole = "user" | "assistant" | "tool" | "system";
