// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Typed JSON envelope nexo publishes after every accepted
 * webhook request.
 *
 * Subscribers correlate events via `envelope_id` (deterministic
 * dedup) and `received_at_ms` (late-binding analytics).
 * `headers_subset` is a defensive allowlist — secrets like
 * `Authorization` / `Cookie` / signature headers are stripped
 * before publish, so a NATS subscriber sees only non-secret
 * correlation IDs.
 *
 * Unlike [`crate::BindingContext`], this struct is intentionally
 * *not* `#[non_exhaustive]`: it represents a wire-shape value
 * constructed on both sides (the daemon writes it; tests +
 * mocks build it via struct-literal). Field additions are
 * semver-major because the JSON wire shape changes regardless.
 *
 * # Example
 *
 * Microapps typically deserialise the envelope from a NATS
 * payload:
 *
 * ```
 * use nexo_tool_meta::WebhookEnvelope;
 *
 * let payload = serde_json::json!({
 *     "schema": 1,
 *     "source_id": "github_main",
 *     "event_kind": "pull_request",
 *     "body_json": {"action": "opened"},
 *     "headers_subset": {},
 *     "received_at_ms": 0,
 *     "envelope_id": "00000000-0000-0000-0000-000000000000",
 *     "client_ip": null
 * });
 * let env: WebhookEnvelope = serde_json::from_value(payload).unwrap();
 * assert_eq!(env.schema, 1);
 * assert_eq!(env.source_id, "github_main");
 * ```
 */
export type WebhookEnvelope = { 
/**
 * Wire-shape version. Always [`ENVELOPE_SCHEMA_VERSION`].
 */
schema: number, 
/**
 * Operator-assigned source identifier — matches the
 * `webhook_receiver.sources[].id` YAML field.
 */
source_id: string, 
/**
 * Event kind extracted from the inbound request (header or
 * JSON body path, per source config).
 */
event_kind: string, 
/**
 * Inbound body, parsed as JSON. Non-JSON bodies are wrapped
 * as `{ "raw_base64": "..." }` upstream.
 */
body_json: JsonValue, 
/**
 * Allowlisted headers forwarded for downstream correlation.
 * Authorization / Cookie / signature headers are stripped.
 */
headers_subset: { [key in string]: string }, 
/**
 * Server-side receipt timestamp in milliseconds since epoch.
 */
received_at_ms: bigint, 
/**
 * Random per-envelope identifier — useful for dedup.
 */
envelope_id: string, 
/**
 * Resolved client IP (after trusted-proxy logic). `None`
 * for envelopes built outside an HTTP request context.
 */
client_ip: string | null, };
