#!/usr/bin/env bash
set -euo pipefail

# claude-switch.sh — toggle Claude Code backend between DeepSeek and native Anthropic
# Source: https://api-docs.deepseek.com/guides/agent_integrations/claude_code

ENV_FILE="${HOME}/.claude-backend"

DEEPSEEK_BASE_URL="https://api.deepseek.com/anthropic"
DEEPSEEK_MODEL="deepseek-v4-pro"
DEEPSEEK_FLASH_MODEL="deepseek-v4-flash"

usage() {
    cat <<'EOF'
Usage: source scripts/claude-switch.sh <command>

Commands:
  deepseek [api-key]   Switch Claude Code to use DeepSeek as backend.
                       Reads DEEPSEEK_API_KEY env var, or pass it as argument.
  native               Switch Claude Code back to native Anthropic (default).
  status               Show current backend configuration.
  help                 Show this help.

Examples:
  source scripts/claude-switch.sh deepseek sk-xxxx
  source scripts/claude-switch.sh native
  source scripts/claude-switch.sh status

Note: Must be sourced (not executed) so env vars affect the current shell.
      The config persists across shells via ~/.claude-backend.
      Add 'source ~/.claude-backend' to your ~/.bashrc or ~/.zshrc to auto-load.
EOF
}

switch_deepseek() {
    local api_key="${1:-${DEEPSEEK_API_KEY:-}}"

    if [ -z "${api_key}" ]; then
        echo "ERROR: DeepSeek API key required."
        echo "  Set DEEPSEEK_API_KEY env var, or pass it: source scripts/claude-switch.sh deepseek sk-xxxx"
        echo "  Get your key at: https://platform.deepseek.com/api_keys"
        return 1
    fi

    cat >"${ENV_FILE}" <<ENVEOF
# Claude Code → DeepSeek backend
# Generated by claude-switch.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
export ANTHROPIC_BASE_URL="${DEEPSEEK_BASE_URL}"
export ANTHROPIC_AUTH_TOKEN="${api_key}"
export ANTHROPIC_MODEL="${DEEPSEEK_MODEL}"
export ANTHROPIC_DEFAULT_OPUS_MODEL="${DEEPSEEK_MODEL}"
export ANTHROPIC_DEFAULT_SONNET_MODEL="${DEEPSEEK_MODEL}"
export ANTHROPIC_DEFAULT_HAIKU_MODEL="${DEEPSEEK_FLASH_MODEL}"
export CLAUDE_CODE_SUBAGENT_MODEL="${DEEPSEEK_FLASH_MODEL}"
export CLAUDE_CODE_EFFORT_LEVEL="max"
ENVEOF

    # shellcheck source=/dev/null
    source "${ENV_FILE}"
    echo "[claude-switch] Backend → DeepSeek (${DEEPSEEK_MODEL})"
    echo "[claude-switch] Config saved → ${ENV_FILE}"
}

switch_native() {
    rm -f "${ENV_FILE}"

    unset ANTHROPIC_BASE_URL
    unset ANTHROPIC_AUTH_TOKEN
    unset ANTHROPIC_MODEL
    unset ANTHROPIC_DEFAULT_OPUS_MODEL
    unset ANTHROPIC_DEFAULT_SONNET_MODEL
    unset ANTHROPIC_DEFAULT_HAIKU_MODEL
    unset CLAUDE_CODE_SUBAGENT_MODEL
    unset CLAUDE_CODE_EFFORT_LEVEL

    echo "[claude-switch] Backend → Native Anthropic (default)"
    echo "[claude-switch] Config removed → ${ENV_FILE}"
}

show_status() {
    if [ -f "${ENV_FILE}" ]; then
        echo "[claude-switch] Backend: DeepSeek"
        echo "  ANTHROPIC_BASE_URL = ${ANTHROPIC_BASE_URL:-$(grep ANTHROPIC_BASE_URL "${ENV_FILE}" 2>/dev/null | cut -d'"' -f2 || echo 'not set')}"
        echo "  ANTHROPIC_MODEL    = ${ANTHROPIC_MODEL:-$(grep 'ANTHROPIC_MODEL=' "${ENV_FILE}" 2>/dev/null | cut -d'"' -f2 || echo 'not set')}"
    else
        echo "[claude-switch] Backend: Native Anthropic (no override)"
    fi
}

# Auto-load persisted config if present and not already overridden
if [ -f "${ENV_FILE}" ] && [ -z "${ANTHROPIC_BASE_URL:-}" ]; then
    # shellcheck source=/dev/null
    source "${ENV_FILE}"
fi

case "${1:-help}" in
    deepseek|ds)
        shift
        switch_deepseek "$@"
        ;;
    native|n|claude|c)
        switch_native
        ;;
    status|s|show)
        show_status
        ;;
    help|--help|-h|*)
        usage
        ;;
esac
