#!/usr/bin/env bash
# Phase 83.12.ts-types-codegen — regenerate
# `agent-creator-microapp/frontend/src/api/types.gen.ts` from the
# Rust source-of-truth (`nexo-tool-meta` `#[ts(export)]` structs).
#
# Run from anywhere; the script `cd`s to the proyecto repo root
# automatically.
#
# Usage:
#   bash scripts/regen-ts-types.sh
#
# What it does:
#   1. Wipes the staging directory `/tmp/nexo-ts-out`.
#   2. Runs `cargo test --features=ts-export -p nexo-tool-meta`
#      with `TS_RS_EXPORT_DIR` set to that staging dir. ts-rs's
#      auto-generated tests write one `.ts` file per type marked
#      `#[ts(export)]`.
#   3. Concatenates the per-type files (sorted alphabetically for
#      diff stability) into a single `types.gen.ts` with a banner
#      header at `agent-creator-microapp/frontend/src/api/`.
#   4. Cleans up the staging directory.
#
# The CI lint script `lint-ts-types-sync.sh` regenerates and diffs
# against the checked-in file to catch drift.

set -euo pipefail

cd "$(dirname "$0")/.."

STAGE_DIR="/tmp/nexo-ts-out-$$"
FINAL_FILE="../agent-creator-microapp/frontend/src/api/types.gen.ts"

if [[ ! -d "../agent-creator-microapp/frontend/src/api" ]]; then
    echo "::error::agent-creator-microapp not present alongside proyecto" >&2
    echo "Expected: $(pwd)/../agent-creator-microapp/frontend/src/api/" >&2
    exit 1
fi

# Clean staging dir.
rm -rf "$STAGE_DIR"
mkdir -p "$STAGE_DIR"
trap "rm -rf $STAGE_DIR" EXIT

# Run ts-rs's auto-generated export tests.
# `TS_RS_LARGE_INT=number` maps Rust `u64`/`i64` to TS `number`
# (matches agent-creator's existing hand-written types — `seq` and
# `at_ms` are read as JS numbers, not bigints, despite the lossy
# precision past 2^53).
echo "→ Running cargo test --features=ts-export to emit per-type .ts files…"
TS_RS_EXPORT_DIR="$STAGE_DIR" \
TS_RS_LARGE_INT=number \
    cargo test \
        --features=ts-export \
        -p nexo-tool-meta \
        --quiet 2>&1 \
    | grep -E "^test|^error|^FAILED" \
    | tail -5 || true

# Sanity check: at least 16 per-type files expected (the count of
# `#[ts(export)]` types). Any nested directories ts-rs creates
# (e.g. `serde_json/`) we ignore — only the top-level .ts files
# are wire types we care about.
TS_FILES=$(find "$STAGE_DIR" -maxdepth 1 -name "*.ts" -type f | sort)
COUNT=$(echo "$TS_FILES" | grep -c "^." || true)
if [[ "$COUNT" -lt 10 ]]; then
    echo "::error::Expected at least 10 .ts files, got $COUNT" >&2
    ls -la "$STAGE_DIR" >&2
    exit 1
fi

# Concatenate into types.gen.ts with banner. Strip per-file
# `import type { X } from "./X"` lines because all types live in
# the same final file (no cross-file imports needed). Also strip
# the per-file `// This file was generated by ts-rs` boilerplate
# header since the banner above already documents the source.
{
    cat <<'HEADER'
// AUTOGENERATED — do not edit by hand.
//
// Generated from `nexo-tool-meta` `#[ts(export)]` structs by
// `proyecto/scripts/regen-ts-types.sh`. The CI lint
// `proyecto/scripts/lint-ts-types-sync.sh` ensures this file
// matches the current Rust sources at HEAD; if it doesn't,
// regenerate via:
//
//   cd proyecto && bash scripts/regen-ts-types.sh
//
// Source of truth: `proyecto/crates/tool-meta/src/`.

/**
 * Recursive JSON value type — mirrors `serde_json::Value` on the
 * Rust side. ts-rs would normally emit a separate file for this;
 * we inline it here so the single-file `types.gen.ts` is
 * self-contained.
 */
export type JsonValue =
  | null
  | boolean
  | number
  | string
  | JsonValue[]
  | { [key: string]: JsonValue };
HEADER
    for f in $TS_FILES; do
        echo
        echo "// ─── $(basename "$f") ────────────────────────────────────"
        # Drop ts-rs boilerplate header (single line) + every cross-
        # file import (they're all co-located in this single file).
        grep -v '^// This file was generated by \[ts-rs\]' "$f" \
            | grep -v '^import type {.*} from "\./.*";$' \
            | sed -E 's/^[[:space:]]*$//' \
            | cat -s
    done
} > "$FINAL_FILE"

LINES=$(wc -l < "$FINAL_FILE")
echo "✅ Wrote $FINAL_FILE ($COUNT types, $LINES lines)."
