//! Phase 48 follow-up — interactive email setup wizard.
//!
//! Operators previously had to hand-edit `config/plugins/email.yaml`
//! and `secrets/email/<inst>.toml` (the latter at mode `0o600`).
//! This wizard streamlines the common cases: pick an instance,
//! enter the address, accept the auto-detected provider preset (or
//! override), pick an auth kind, persist both files atomically.
//!
//! Pure-helpers (`derive_default_instance`, `auth_kind_choices`,
//! `render_account_block`, `serialise_secret_toml`) are unit-
//! tested. The interactive `run_email_wizard` orchestrator wraps
//! them with `dialoguer` prompts; testing the prompts requires a
//! TTY mock that's out of scope here.

use std::path::{Path, PathBuf};

use anyhow::{anyhow, Context, Result};
use dialoguer::{theme::ColorfulTheme, Confirm, Input, Password, Select};
use nexo_plugin_email::provider_hint;

use nexo_config::types::plugins::{EmailProvider, TlsMode};

/// In-memory snapshot the wizard hands to the writers. Decoupled
/// from the YAML/TOML serialisers so tests can drive them directly.
#[derive(Debug, Clone, PartialEq)]
pub struct EmailAccountForm {
    pub instance: String,
    pub address: String,
    pub provider: EmailProvider,
    pub imap_host: String,
    pub imap_port: u16,
    pub imap_tls: TlsMode,
    pub smtp_host: String,
    pub smtp_port: u16,
    pub smtp_tls: TlsMode,
    pub auth: AuthForm,
}

#[derive(Debug, Clone, PartialEq)]
pub enum AuthForm {
    Password { username: String, password: String },
    Oauth2Static { username: String, access_token: String },
    Oauth2Google { username: String, google_account_id: String },
}

/// Pick a default instance id from the address localpart, falling
/// back to `"ops"` for malformed inputs. Lowercased and trimmed of
/// dots/plus tags so an address like `Alice.Doe+work@gmail.com`
/// becomes `alice.doe`.
pub fn derive_default_instance(address: &str) -> String {
    let local = address
        .split_once('@')
        .map(|(l, _)| l)
        .unwrap_or(address)
        .trim();
    let local = local.split_once('+').map(|(l, _)| l).unwrap_or(local);
    let cleaned = local.to_ascii_lowercase();
    if cleaned.is_empty() {
        "ops".into()
    } else {
        cleaned
    }
}

pub fn auth_kind_choices() -> &'static [&'static str] {
    &[
        "Password (app password / IMAP password)",
        "OAuth2 static token (bring-your-own bearer)",
        "OAuth2 Google (reuse google-auth.yaml account)",
    ]
}

/// Serialise a single account YAML block (without the surrounding
/// `accounts:` array). Pure — used both by the writer and by
/// tests.
pub fn render_account_block(form: &EmailAccountForm) -> String {
    fn tls_label(t: &TlsMode) -> &'static str {
        match t {
            TlsMode::ImplicitTls => "implicit_tls",
            TlsMode::Starttls => "starttls",
            TlsMode::Plain => "plain",
        }
    }
    fn provider_label(p: &EmailProvider) -> &'static str {
        match p {
            EmailProvider::Gmail => "gmail",
            EmailProvider::Outlook => "outlook",
            EmailProvider::Yahoo => "yahoo",
            EmailProvider::Icloud => "icloud",
            EmailProvider::Custom => "custom",
        }
    }
    format!(
        "  - instance: {}\n    address: {}\n    provider: {}\n    imap: {{ host: {}, port: {}, tls: {} }}\n    smtp: {{ host: {}, port: {}, tls: {} }}\n",
        form.instance,
        form.address,
        provider_label(&form.provider),
        form.imap_host,
        form.imap_port,
        tls_label(&form.imap_tls),
        form.smtp_host,
        form.smtp_port,
        tls_label(&form.smtp_tls),
    )
}

/// Render the TOML secret file body. The caller is responsible for
/// `0o600` enforcement on Unix; this helper is pure-string.
pub fn serialise_secret_toml(form: &EmailAccountForm) -> String {
    match &form.auth {
        AuthForm::Password { username, password } => format!(
            "# Generated by `nexo setup` — never commit this file.\n# Phase 48 follow-up — email wizard.\n\n[auth]\nkind = \"password\"\nusername = \"{}\"\npassword = \"{}\"\n",
            username, password
        ),
        AuthForm::Oauth2Static {
            username,
            access_token,
        } => format!(
            "# Generated by `nexo setup` — never commit this file.\n# Phase 48 follow-up — email wizard.\n\n[auth]\nkind = \"oauth2_static\"\nusername = \"{}\"\naccess_token = \"{}\"\n",
            username, access_token
        ),
        AuthForm::Oauth2Google {
            username,
            google_account_id,
        } => format!(
            "# Generated by `nexo setup` — never commit this file.\n# Phase 48 follow-up — email wizard.\n\n[auth]\nkind = \"oauth2_google\"\nusername = \"{}\"\ngoogle_account_id = \"{}\"\n",
            username, google_account_id
        ),
    }
}

/// Atomic write of `<secrets_dir>/email/<instance>.toml` at mode
/// `0o600` (Unix). Uses a temp sibling + rename so a partial write
/// never lands. On Windows the `chmod` step is a no-op.
pub fn write_secret_toml(
    secrets_dir: &Path,
    instance: &str,
    body: &str,
) -> Result<PathBuf> {
    let dir = secrets_dir.join("email");
    std::fs::create_dir_all(&dir)
        .with_context(|| format!("create {}", dir.display()))?;
    let final_path = dir.join(format!("{instance}.toml"));
    let tmp_path = dir.join(format!("{instance}.toml.tmp.{}", std::process::id()));
    std::fs::write(&tmp_path, body).with_context(|| format!("write {}", tmp_path.display()))?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(&tmp_path, std::fs::Permissions::from_mode(0o600))
            .with_context(|| format!("chmod 0o600 {}", tmp_path.display()))?;
    }
    std::fs::rename(&tmp_path, &final_path)
        .with_context(|| format!("rename {} → {}", tmp_path.display(), final_path.display()))?;
    Ok(final_path)
}

/// Append (or upsert) the rendered account block into
/// `<config_dir>/plugins/email.yaml`. Idempotent: re-running the
/// wizard with the same `instance` rewrites that block in place,
/// other accounts preserved. v1 uses serde_yaml's regen-from-tree
/// approach which loses comments — acceptable until 48-x adds a
/// comment-preserving editor.
pub fn upsert_email_account_yaml(
    config_dir: &Path,
    form: &EmailAccountForm,
) -> Result<PathBuf> {
    use serde_yaml::Value;
    let path = config_dir.join("plugins").join("email.yaml");
    std::fs::create_dir_all(path.parent().unwrap())
        .with_context(|| format!("create plugins dir {}", path.display()))?;

    let mut root: Value = if path.exists() {
        let raw = std::fs::read_to_string(&path)
            .with_context(|| format!("read {}", path.display()))?;
        serde_yaml::from_str(&raw)
            .with_context(|| format!("parse {} (existing YAML invalid)", path.display()))?
    } else {
        serde_yaml::from_str("email:\n  enabled: true\n  spf_dkim_warn: true\n  accounts: []\n")
            .unwrap()
    };

    let email = root
        .as_mapping_mut()
        .and_then(|m| m.get_mut(Value::String("email".into())))
        .ok_or_else(|| anyhow!("YAML missing top-level `email:` block"))?;
    let email_map = email
        .as_mapping_mut()
        .ok_or_else(|| anyhow!("`email:` is not a mapping"))?;
    let accounts_key = Value::String("accounts".into());
    let accounts = email_map
        .entry(accounts_key.clone())
        .or_insert(Value::Sequence(Vec::new()));
    let accounts_seq = accounts
        .as_sequence_mut()
        .ok_or_else(|| anyhow!("`email.accounts` is not a sequence"))?;

    // Build the new account map directly so we don't have to
    // round-trip our own rendered string through serde_yaml.
    fn tls_label(t: &TlsMode) -> &'static str {
        match t {
            TlsMode::ImplicitTls => "implicit_tls",
            TlsMode::Starttls => "starttls",
            TlsMode::Plain => "plain",
        }
    }
    fn provider_label(p: &EmailProvider) -> &'static str {
        match p {
            EmailProvider::Gmail => "gmail",
            EmailProvider::Outlook => "outlook",
            EmailProvider::Yahoo => "yahoo",
            EmailProvider::Icloud => "icloud",
            EmailProvider::Custom => "custom",
        }
    }
    let mut imap = serde_yaml::Mapping::new();
    imap.insert(Value::String("host".into()), Value::String(form.imap_host.clone()));
    imap.insert(
        Value::String("port".into()),
        Value::Number(serde_yaml::Number::from(form.imap_port)),
    );
    imap.insert(
        Value::String("tls".into()),
        Value::String(tls_label(&form.imap_tls).into()),
    );
    let mut smtp = serde_yaml::Mapping::new();
    smtp.insert(Value::String("host".into()), Value::String(form.smtp_host.clone()));
    smtp.insert(
        Value::String("port".into()),
        Value::Number(serde_yaml::Number::from(form.smtp_port)),
    );
    smtp.insert(
        Value::String("tls".into()),
        Value::String(tls_label(&form.smtp_tls).into()),
    );
    let mut acct = serde_yaml::Mapping::new();
    acct.insert(Value::String("instance".into()), Value::String(form.instance.clone()));
    acct.insert(Value::String("address".into()), Value::String(form.address.clone()));
    acct.insert(
        Value::String("provider".into()),
        Value::String(provider_label(&form.provider).into()),
    );
    acct.insert(Value::String("imap".into()), Value::Mapping(imap));
    acct.insert(Value::String("smtp".into()), Value::Mapping(smtp));
    let new_account = Value::Mapping(acct);

    let mut replaced = false;
    for slot in accounts_seq.iter_mut() {
        let matches = slot
            .as_mapping()
            .and_then(|m| m.get(Value::String("instance".into())))
            .and_then(|v| v.as_str())
            == Some(form.instance.as_str());
        if matches {
            *slot = new_account.clone();
            replaced = true;
            break;
        }
    }
    if !replaced {
        accounts_seq.push(new_account);
    }

    let serialised =
        serde_yaml::to_string(&root).context("serialise email.yaml after upsert")?;
    std::fs::write(&path, serialised).with_context(|| format!("write {}", path.display()))?;
    Ok(path)
}

/// Interactive entry point. Opens prompts via `dialoguer`, builds an
/// `EmailAccountForm`, persists YAML + TOML. Returns the resolved
/// paths so the caller can echo them.
pub fn run_email_wizard(
    config_dir: &Path,
    secrets_dir: &Path,
) -> Result<(PathBuf, PathBuf)> {
    let theme = ColorfulTheme::default();
    println!("Email account wizard");
    println!("--------------------");
    println!("Press Ctrl-C to abort. Existing instance ids are overwritten in place.");

    let address: String = Input::with_theme(&theme)
        .with_prompt("Email address (e.g. ops@example.com)")
        .interact_text()?;
    let address = address.trim().to_string();
    if !address.contains('@') {
        return Err(anyhow!("address must contain '@'"));
    }

    let default_instance = derive_default_instance(&address);
    let instance: String = Input::with_theme(&theme)
        .with_prompt("Instance id (used in `plugin.inbound.email.<instance>`)")
        .default(default_instance)
        .interact_text()?;
    let instance = instance.trim().to_string();

    let domain = address.split_once('@').map(|(_, d)| d).unwrap_or("");
    let hint = provider_hint(domain);
    println!(
        "\nDetected provider: {:?} ({}:{} / {}:{})",
        hint.provider, hint.imap_host, hint.imap_port, hint.smtp_host, hint.smtp_port,
    );
    let accept_preset = Confirm::with_theme(&theme)
        .with_prompt("Use the detected preset?")
        .default(true)
        .interact()?;
    let (imap_host, imap_port, imap_tls, smtp_host, smtp_port, smtp_tls) = if accept_preset {
        (
            hint.imap_host.clone(),
            hint.imap_port,
            hint.imap_tls,
            hint.smtp_host.clone(),
            hint.smtp_port,
            hint.smtp_tls,
        )
    } else {
        let imap_host: String = Input::with_theme(&theme)
            .with_prompt("IMAP host")
            .default(hint.imap_host.clone())
            .interact_text()?;
        let imap_port: u16 = Input::with_theme(&theme)
            .with_prompt("IMAP port")
            .default(hint.imap_port)
            .interact_text()?;
        let smtp_host: String = Input::with_theme(&theme)
            .with_prompt("SMTP host")
            .default(hint.smtp_host.clone())
            .interact_text()?;
        let smtp_port: u16 = Input::with_theme(&theme)
            .with_prompt("SMTP port")
            .default(hint.smtp_port)
            .interact_text()?;
        (
            imap_host,
            imap_port,
            hint.imap_tls,
            smtp_host,
            smtp_port,
            hint.smtp_tls,
        )
    };

    let auth_idx = Select::with_theme(&theme)
        .with_prompt("Auth kind")
        .items(auth_kind_choices())
        .default(if hint.suggest_oauth_google { 2 } else { 0 })
        .interact()?;
    let auth = match auth_idx {
        0 => {
            let username: String = Input::with_theme(&theme)
                .with_prompt("Username")
                .default(address.clone())
                .interact_text()?;
            let password = Password::with_theme(&theme)
                .with_prompt("Password / app password")
                .interact()?;
            AuthForm::Password { username, password }
        }
        1 => {
            let username: String = Input::with_theme(&theme)
                .with_prompt("Username")
                .default(address.clone())
                .interact_text()?;
            let access_token = Password::with_theme(&theme)
                .with_prompt("OAuth2 access token")
                .interact()?;
            AuthForm::Oauth2Static {
                username,
                access_token,
            }
        }
        _ => {
            let username: String = Input::with_theme(&theme)
                .with_prompt("Username")
                .default(address.clone())
                .interact_text()?;
            let google_account_id: String = Input::with_theme(&theme)
                .with_prompt("Google account id (from google-auth.yaml)")
                .interact_text()?;
            AuthForm::Oauth2Google {
                username,
                google_account_id,
            }
        }
    };

    let form = EmailAccountForm {
        instance,
        address,
        provider: hint.provider,
        imap_host,
        imap_port,
        imap_tls,
        smtp_host,
        smtp_port,
        smtp_tls,
        auth,
    };

    let yaml_path = upsert_email_account_yaml(config_dir, &form)?;
    let toml_path =
        write_secret_toml(secrets_dir, &form.instance, &serialise_secret_toml(&form))?;
    println!("\n✔ wrote {}", yaml_path.display());
    println!("✔ wrote {} (mode 0o600)", toml_path.display());
    Ok((yaml_path, toml_path))
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    fn form(instance: &str, address: &str) -> EmailAccountForm {
        EmailAccountForm {
            instance: instance.into(),
            address: address.into(),
            provider: EmailProvider::Custom,
            imap_host: "imap.example.com".into(),
            imap_port: 993,
            imap_tls: TlsMode::ImplicitTls,
            smtp_host: "smtp.example.com".into(),
            smtp_port: 587,
            smtp_tls: TlsMode::Starttls,
            auth: AuthForm::Password {
                username: address.into(),
                password: "hunter2".into(),
            },
        }
    }

    #[test]
    fn derive_default_instance_pulls_localpart() {
        assert_eq!(derive_default_instance("ops@example.com"), "ops");
    }

    #[test]
    fn derive_default_instance_strips_plus_tag() {
        assert_eq!(
            derive_default_instance("Alice.Doe+work@gmail.com"),
            "alice.doe"
        );
    }

    #[test]
    fn derive_default_instance_falls_back_to_ops() {
        assert_eq!(derive_default_instance(""), "ops");
        assert_eq!(derive_default_instance("@x"), "ops");
    }

    #[test]
    fn render_account_block_matches_yaml_shape() {
        let body = render_account_block(&form("ops", "ops@x.com"));
        assert!(body.contains("  - instance: ops\n"));
        assert!(body.contains("    address: ops@x.com\n"));
        assert!(body.contains("    provider: custom\n"));
        assert!(body.contains("imap.example.com"));
        assert!(body.contains("smtp.example.com"));
    }

    #[test]
    fn serialise_secret_toml_password() {
        let s = serialise_secret_toml(&form("ops", "ops@x.com"));
        assert!(s.contains("kind = \"password\""));
        assert!(s.contains("password = \"hunter2\""));
    }

    #[test]
    fn serialise_secret_toml_oauth2_google() {
        let mut f = form("ops", "ops@x.com");
        f.auth = AuthForm::Oauth2Google {
            username: "ops@gmail.com".into(),
            google_account_id: "ops".into(),
        };
        let s = serialise_secret_toml(&f);
        assert!(s.contains("kind = \"oauth2_google\""));
        assert!(s.contains("google_account_id = \"ops\""));
    }

    #[test]
    fn write_secret_toml_atomic_and_chmod() {
        let dir = tempdir().unwrap();
        let path = write_secret_toml(dir.path(), "ops", "[auth]\nkind=\"password\"\n").unwrap();
        assert!(path.ends_with("email/ops.toml"));
        let body = std::fs::read_to_string(&path).unwrap();
        assert!(body.contains("password"));
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mode = std::fs::metadata(&path).unwrap().permissions().mode() & 0o777;
            assert_eq!(mode, 0o600);
        }
    }

    #[test]
    fn upsert_creates_yaml_when_absent() {
        let dir = tempdir().unwrap();
        let path = upsert_email_account_yaml(dir.path(), &form("ops", "ops@x.com")).unwrap();
        let body = std::fs::read_to_string(&path).unwrap();
        assert!(body.contains("ops@x.com"));
        assert!(body.contains("instance: ops"));
    }

    #[test]
    fn upsert_replaces_existing_instance_in_place() {
        let dir = tempdir().unwrap();
        let mut f1 = form("ops", "old@x.com");
        let mut f2 = form("ops", "new@x.com");
        f2.imap_host = "imap.new.com".into();
        f1.imap_host = "imap.old.com".into();
        upsert_email_account_yaml(dir.path(), &f1).unwrap();
        let path = upsert_email_account_yaml(dir.path(), &f2).unwrap();
        let body = std::fs::read_to_string(&path).unwrap();
        assert!(body.contains("new@x.com"));
        assert!(!body.contains("old@x.com"));
        assert!(body.contains("imap.new.com"));
    }

    #[test]
    fn upsert_appends_new_instance_alongside_existing() {
        let dir = tempdir().unwrap();
        upsert_email_account_yaml(dir.path(), &form("ops", "ops@x.com")).unwrap();
        let path =
            upsert_email_account_yaml(dir.path(), &form("support", "support@x.com")).unwrap();
        let body = std::fs::read_to_string(&path).unwrap();
        assert!(body.contains("ops@x.com"));
        assert!(body.contains("support@x.com"));
    }
}
