//! Phase 48 follow-up — interactive email setup wizard.
//!
//! Operators previously had to hand-edit `config/plugins/email.yaml`
//! and `secrets/email/<inst>.toml` (the latter at mode `0o600`).
//! This wizard streamlines the common cases: pick an instance,
//! enter the address, accept the auto-detected provider preset (or
//! override), pick an auth kind, persist both files atomically.
//!
//! Phase 48 UX polish — `run_email_wizard` is now a menu loop
//! (List / Add / Edit / Delete / Probe). The single-shot add flow
//! lives in `run_add_or_edit_account` and is reused by both Add and
//! Edit. Probe runs IMAP login + SMTP test_connection against the
//! form so credentials are validated before persisting.
//!
//! Pure-helpers (`derive_default_instance`, `auth_kind_choices`,
//! `render_account_block`, `serialise_secret_toml`) are unit-
//! tested. The interactive `run_email_wizard` orchestrator wraps
//! them with `dialoguer` prompts; testing the prompts requires a
//! TTY mock that's out of scope here.

use std::path::{Path, PathBuf};
use std::sync::Arc;

use anyhow::{anyhow, Context, Result};
use dialoguer::{theme::ColorfulTheme, Confirm, Input, Password, Select};
use nexo_auth::email::{EmailAccount, EmailAuth};
use nexo_auth::google::GoogleCredentialStore;
use nexo_plugin_email::imap_conn::ImapConnection;
use nexo_plugin_email::provider_hint;
use nexo_plugin_email::smtp_conn::SmtpClient;
use nexo_plugin_email::spf_dkim::{check_alignment, decide_warns};
use secrecy::SecretString;

use nexo_config::types::plugins::{EmailProvider, ImapEndpoint, SmtpEndpoint, TlsMode};

/// In-memory snapshot the wizard hands to the writers. Decoupled
/// from the YAML/TOML serialisers so tests can drive them directly.
#[derive(Debug, Clone, PartialEq)]
pub struct EmailAccountForm {
    pub instance: String,
    pub address: String,
    pub provider: EmailProvider,
    pub imap_host: String,
    pub imap_port: u16,
    pub imap_tls: TlsMode,
    pub smtp_host: String,
    pub smtp_port: u16,
    pub smtp_tls: TlsMode,
    pub auth: AuthForm,
}

#[derive(Debug, Clone, PartialEq)]
pub enum AuthForm {
    Password {
        username: String,
        password: String,
    },
    Oauth2Static {
        username: String,
        access_token: String,
    },
    Oauth2Google {
        username: String,
        google_account_id: String,
    },
}

/// Pick a default instance id from the address localpart, falling
/// back to `"ops"` for malformed inputs. Lowercased and trimmed of
/// dots/plus tags so an address like `Alice.Doe+work@gmail.com`
/// becomes `alice.doe`.
pub fn derive_default_instance(address: &str) -> String {
    let local = address
        .split_once('@')
        .map(|(l, _)| l)
        .unwrap_or(address)
        .trim();
    let local = local.split_once('+').map(|(l, _)| l).unwrap_or(local);
    let cleaned = local.to_ascii_lowercase();
    if cleaned.is_empty() {
        "ops".into()
    } else {
        cleaned
    }
}

pub fn auth_kind_choices() -> &'static [&'static str] {
    &[
        "Password (app password / IMAP password)",
        "OAuth2 static token (bring-your-own bearer)",
        "OAuth2 Google (reuse google-auth.yaml account)",
    ]
}

/// Serialise a single account YAML block (without the surrounding
/// `accounts:` array). Pure — used both by the writer and by
/// tests.
pub fn render_account_block(form: &EmailAccountForm) -> String {
    fn tls_label(t: &TlsMode) -> &'static str {
        match t {
            TlsMode::ImplicitTls => "implicit_tls",
            TlsMode::Starttls => "starttls",
            TlsMode::Plain => "plain",
        }
    }
    fn provider_label(p: &EmailProvider) -> &'static str {
        match p {
            EmailProvider::Gmail => "gmail",
            EmailProvider::Outlook => "outlook",
            EmailProvider::Yahoo => "yahoo",
            EmailProvider::Icloud => "icloud",
            EmailProvider::Custom => "custom",
        }
    }
    format!(
        "  - instance: {}\n    address: {}\n    provider: {}\n    imap: {{ host: {}, port: {}, tls: {} }}\n    smtp: {{ host: {}, port: {}, tls: {} }}\n",
        form.instance,
        form.address,
        provider_label(&form.provider),
        form.imap_host,
        form.imap_port,
        tls_label(&form.imap_tls),
        form.smtp_host,
        form.smtp_port,
        tls_label(&form.smtp_tls),
    )
}

/// Render the TOML secret file body. The caller is responsible for
/// `0o600` enforcement on Unix; this helper is pure-string.
pub fn serialise_secret_toml(form: &EmailAccountForm) -> String {
    match &form.auth {
        AuthForm::Password { username, password } => format!(
            "# Generated by `nexo setup` — never commit this file.\n# Phase 48 follow-up — email wizard.\n\n[auth]\nkind = \"password\"\nusername = \"{}\"\npassword = \"{}\"\n",
            username, password
        ),
        AuthForm::Oauth2Static {
            username,
            access_token,
        } => format!(
            "# Generated by `nexo setup` — never commit this file.\n# Phase 48 follow-up — email wizard.\n\n[auth]\nkind = \"oauth2_static\"\nusername = \"{}\"\naccess_token = \"{}\"\n",
            username, access_token
        ),
        AuthForm::Oauth2Google {
            username,
            google_account_id,
        } => format!(
            "# Generated by `nexo setup` — never commit this file.\n# Phase 48 follow-up — email wizard.\n\n[auth]\nkind = \"oauth2_google\"\nusername = \"{}\"\ngoogle_account_id = \"{}\"\n",
            username, google_account_id
        ),
    }
}

/// Atomic write of `<secrets_dir>/email/<instance>.toml` at mode
/// `0o600` (Unix). Uses a temp sibling + rename so a partial write
/// never lands. On Windows the `chmod` step is a no-op.
pub fn write_secret_toml(secrets_dir: &Path, instance: &str, body: &str) -> Result<PathBuf> {
    let dir = secrets_dir.join("email");
    std::fs::create_dir_all(&dir).with_context(|| format!("create {}", dir.display()))?;
    let final_path = dir.join(format!("{instance}.toml"));
    let tmp_path = dir.join(format!("{instance}.toml.tmp.{}", std::process::id()));
    std::fs::write(&tmp_path, body).with_context(|| format!("write {}", tmp_path.display()))?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(&tmp_path, std::fs::Permissions::from_mode(0o600))
            .with_context(|| format!("chmod 0o600 {}", tmp_path.display()))?;
    }
    std::fs::rename(&tmp_path, &final_path)
        .with_context(|| format!("rename {} → {}", tmp_path.display(), final_path.display()))?;
    Ok(final_path)
}

/// Append (or upsert) the rendered account block into
/// `<config_dir>/plugins/email.yaml`. Idempotent: re-running the
/// wizard with the same `instance` rewrites that block in place,
/// other accounts preserved. v1 uses serde_yaml's regen-from-tree
/// approach which loses comments — acceptable until 48-x adds a
/// comment-preserving editor.
pub fn upsert_email_account_yaml(config_dir: &Path, form: &EmailAccountForm) -> Result<PathBuf> {
    use serde_yaml::Value;
    let path = config_dir.join("plugins").join("email.yaml");
    std::fs::create_dir_all(path.parent().unwrap())
        .with_context(|| format!("create plugins dir {}", path.display()))?;

    let mut root: Value = if path.exists() {
        let raw =
            std::fs::read_to_string(&path).with_context(|| format!("read {}", path.display()))?;
        serde_yaml::from_str(&raw)
            .with_context(|| format!("parse {} (existing YAML invalid)", path.display()))?
    } else {
        serde_yaml::from_str("email:\n  enabled: true\n  spf_dkim_warn: true\n  accounts: []\n")
            .unwrap()
    };

    let email = root
        .as_mapping_mut()
        .and_then(|m| m.get_mut(Value::String("email".into())))
        .ok_or_else(|| anyhow!("YAML missing top-level `email:` block"))?;
    let email_map = email
        .as_mapping_mut()
        .ok_or_else(|| anyhow!("`email:` is not a mapping"))?;
    let accounts_key = Value::String("accounts".into());
    let accounts = email_map
        .entry(accounts_key.clone())
        .or_insert(Value::Sequence(Vec::new()));
    let accounts_seq = accounts
        .as_sequence_mut()
        .ok_or_else(|| anyhow!("`email.accounts` is not a sequence"))?;

    // Build the new account map directly so we don't have to
    // round-trip our own rendered string through serde_yaml.
    fn tls_label(t: &TlsMode) -> &'static str {
        match t {
            TlsMode::ImplicitTls => "implicit_tls",
            TlsMode::Starttls => "starttls",
            TlsMode::Plain => "plain",
        }
    }
    fn provider_label(p: &EmailProvider) -> &'static str {
        match p {
            EmailProvider::Gmail => "gmail",
            EmailProvider::Outlook => "outlook",
            EmailProvider::Yahoo => "yahoo",
            EmailProvider::Icloud => "icloud",
            EmailProvider::Custom => "custom",
        }
    }
    let mut imap = serde_yaml::Mapping::new();
    imap.insert(
        Value::String("host".into()),
        Value::String(form.imap_host.clone()),
    );
    imap.insert(
        Value::String("port".into()),
        Value::Number(serde_yaml::Number::from(form.imap_port)),
    );
    imap.insert(
        Value::String("tls".into()),
        Value::String(tls_label(&form.imap_tls).into()),
    );
    let mut smtp = serde_yaml::Mapping::new();
    smtp.insert(
        Value::String("host".into()),
        Value::String(form.smtp_host.clone()),
    );
    smtp.insert(
        Value::String("port".into()),
        Value::Number(serde_yaml::Number::from(form.smtp_port)),
    );
    smtp.insert(
        Value::String("tls".into()),
        Value::String(tls_label(&form.smtp_tls).into()),
    );
    let mut acct = serde_yaml::Mapping::new();
    acct.insert(
        Value::String("instance".into()),
        Value::String(form.instance.clone()),
    );
    acct.insert(
        Value::String("address".into()),
        Value::String(form.address.clone()),
    );
    acct.insert(
        Value::String("provider".into()),
        Value::String(provider_label(&form.provider).into()),
    );
    acct.insert(Value::String("imap".into()), Value::Mapping(imap));
    acct.insert(Value::String("smtp".into()), Value::Mapping(smtp));
    let new_account = Value::Mapping(acct);

    let mut replaced = false;
    for slot in accounts_seq.iter_mut() {
        let matches = slot
            .as_mapping()
            .and_then(|m| m.get(Value::String("instance".into())))
            .and_then(|v| v.as_str())
            == Some(form.instance.as_str());
        if matches {
            *slot = new_account.clone();
            replaced = true;
            break;
        }
    }
    if !replaced {
        accounts_seq.push(new_account);
    }

    let serialised = serde_yaml::to_string(&root).context("serialise email.yaml after upsert")?;
    std::fs::write(&path, serialised).with_context(|| format!("write {}", path.display()))?;
    Ok(path)
}

/// One row of `list_accounts` — what we show in the menu's "List"
/// branch and what `Edit`/`Delete` pick from.
#[derive(Debug, Clone, PartialEq)]
pub struct AccountSummary {
    pub instance: String,
    pub address: String,
    pub provider: String,
    pub imap_host: String,
    pub smtp_host: String,
    pub has_secret_toml: bool,
}

/// Parse `<config_dir>/plugins/email.yaml` and return one summary
/// per `accounts:` entry, plus a flag for whether the matching
/// `<secrets_dir>/email/<instance>.toml` exists.
pub fn list_accounts(config_dir: &Path, secrets_dir: &Path) -> Result<Vec<AccountSummary>> {
    let path = config_dir.join("plugins").join("email.yaml");
    if !path.exists() {
        return Ok(vec![]);
    }
    let raw = std::fs::read_to_string(&path).with_context(|| format!("read {}", path.display()))?;
    let root: serde_yaml::Value = serde_yaml::from_str(&raw)
        .with_context(|| format!("parse {} (existing YAML invalid)", path.display()))?;
    let accounts = root
        .as_mapping()
        .and_then(|m| m.get(serde_yaml::Value::String("email".into())))
        .and_then(|v| v.as_mapping())
        .and_then(|m| m.get(serde_yaml::Value::String("accounts".into())))
        .and_then(|v| v.as_sequence())
        .cloned()
        .unwrap_or_default();
    let mut out = Vec::with_capacity(accounts.len());
    for acct in accounts {
        let map = match acct.as_mapping() {
            Some(m) => m,
            None => continue,
        };
        let s = |k: &str| -> String {
            map.get(serde_yaml::Value::String(k.into()))
                .and_then(|v| v.as_str())
                .unwrap_or("")
                .to_string()
        };
        let nested_str = |outer: &str, inner: &str| -> String {
            map.get(serde_yaml::Value::String(outer.into()))
                .and_then(|v| v.as_mapping())
                .and_then(|m| m.get(serde_yaml::Value::String(inner.into())))
                .and_then(|v| v.as_str())
                .unwrap_or("")
                .to_string()
        };
        let instance = s("instance");
        if instance.is_empty() {
            continue;
        }
        let toml_exists = secrets_dir
            .join("email")
            .join(format!("{instance}.toml"))
            .exists();
        out.push(AccountSummary {
            instance,
            address: s("address"),
            provider: s("provider"),
            imap_host: nested_str("imap", "host"),
            smtp_host: nested_str("smtp", "host"),
            has_secret_toml: toml_exists,
        });
    }
    Ok(out)
}

/// Remove an account from `email.yaml` (by `instance`) and delete
/// its secret TOML. Returns `Ok(())` even if the secret was already
/// missing — the operation is idempotent so a half-applied previous
/// run can be cleaned up safely.
pub fn delete_account(config_dir: &Path, secrets_dir: &Path, instance: &str) -> Result<()> {
    use serde_yaml::Value;
    let path = config_dir.join("plugins").join("email.yaml");
    if !path.exists() {
        return Err(anyhow!(
            "no email.yaml at {} — nothing to delete",
            path.display()
        ));
    }
    let raw = std::fs::read_to_string(&path).with_context(|| format!("read {}", path.display()))?;
    let mut root: Value =
        serde_yaml::from_str(&raw).with_context(|| format!("parse {}", path.display()))?;
    let accounts_seq = root
        .as_mapping_mut()
        .and_then(|m| m.get_mut(Value::String("email".into())))
        .and_then(|v| v.as_mapping_mut())
        .and_then(|m| m.get_mut(Value::String("accounts".into())))
        .and_then(|v| v.as_sequence_mut())
        .ok_or_else(|| {
            anyhow!(
                "`email.accounts` missing or malformed in {}",
                path.display()
            )
        })?;
    let before = accounts_seq.len();
    accounts_seq.retain(|slot| {
        slot.as_mapping()
            .and_then(|m| m.get(Value::String("instance".into())))
            .and_then(|v| v.as_str())
            != Some(instance)
    });
    if accounts_seq.len() == before {
        return Err(anyhow!(
            "no account with instance '{instance}' in {}",
            path.display()
        ));
    }
    let body = serde_yaml::to_string(&root).context("serialise email.yaml after delete")?;
    std::fs::write(&path, body).with_context(|| format!("write {}", path.display()))?;

    let toml_path = secrets_dir.join("email").join(format!("{instance}.toml"));
    if toml_path.exists() {
        std::fs::remove_file(&toml_path)
            .with_context(|| format!("delete {}", toml_path.display()))?;
    }
    Ok(())
}

/// Render a human-readable preview of what the wizard is about to
/// write. Used by the review screen so the operator can spot typos
/// before secrets land on disk.
pub fn render_review(form: &EmailAccountForm) -> String {
    fn tls_label(t: &TlsMode) -> &'static str {
        match t {
            TlsMode::ImplicitTls => "implicit_tls",
            TlsMode::Starttls => "starttls",
            TlsMode::Plain => "plain",
        }
    }
    let auth = match &form.auth {
        AuthForm::Password { username, .. } => format!("password (user={username}, pwd=<hidden>)"),
        AuthForm::Oauth2Static { username, .. } => {
            format!("oauth2_static (user={username}, token=<hidden>)")
        }
        AuthForm::Oauth2Google {
            username,
            google_account_id,
        } => format!("oauth2_google (user={username}, google_account_id={google_account_id})"),
    };
    format!(
        "  instance : {}\n  address  : {}\n  provider : {:?}\n  imap     : {}:{} ({})\n  smtp     : {}:{} ({})\n  auth     : {}",
        form.instance,
        form.address,
        form.provider,
        form.imap_host,
        form.imap_port,
        tls_label(&form.imap_tls),
        form.smtp_host,
        form.smtp_port,
        tls_label(&form.smtp_tls),
        auth,
    )
}

/// IMAP+SMTP probe report. Each leg is independently `Ok` / `Err`
/// so the operator sees both diagnostics — a working IMAP with a
/// broken SMTP is the most common misconfiguration shape.
#[derive(Debug)]
pub struct ProbeReport {
    pub imap: std::result::Result<String, String>,
    pub smtp: std::result::Result<String, String>,
    /// SPF/DKIM warnings for the sender domain. `None` when the
    /// probe was skipped (DNS error, empty domain). Empty vec means
    /// the domain looks aligned. Non-empty means the operator
    /// should fix DNS before relying on this account for outbound —
    /// not a hard fail because some setups intentionally rely on
    /// the relay's SPF/DKIM (Mailgun-as-relay etc.).
    pub spf_dkim_warns: Option<Vec<String>>,
}

impl ProbeReport {
    pub fn ok(&self) -> bool {
        self.imap.is_ok() && self.smtp.is_ok()
    }
}

/// Read `<config_dir>/plugins/google-auth.yaml` and return the
/// account ids the operator can pick when wiring `OAuth2Google` for
/// email. Returns empty when the file is missing or has no
/// accounts. Tolerant of a malformed file (returns empty + lets the
/// caller fall back to the free-text prompt).
pub fn list_google_account_ids(config_dir: &Path) -> Vec<String> {
    let path = config_dir.join("plugins").join("google-auth.yaml");
    let raw = match std::fs::read_to_string(&path) {
        Ok(s) => s,
        Err(_) => return vec![],
    };
    let root: serde_yaml::Value = match serde_yaml::from_str(&raw) {
        Ok(v) => v,
        Err(_) => return vec![],
    };
    root.as_mapping()
        .and_then(|m| m.get(serde_yaml::Value::String("google_auth".into())))
        .and_then(|v| v.as_mapping())
        .and_then(|m| m.get(serde_yaml::Value::String("accounts".into())))
        .and_then(|v| v.as_sequence())
        .map(|seq| {
            seq.iter()
                .filter_map(|a| {
                    a.as_mapping()
                        .and_then(|m| m.get(serde_yaml::Value::String("id".into())))
                        .and_then(|v| v.as_str())
                        .map(|s| s.to_string())
                })
                .collect()
        })
        .unwrap_or_default()
}

/// Build a transient `EmailAccount` from the form (no allow_agents,
/// no Google store wiring) and exercise IMAP login + SMTP
/// `test_connection`. OAuth2Google is skipped since resolving the
/// access token requires a live `GoogleCredentialStore`; the
/// operator gets a clear "skipped — daemon will probe at boot" note
/// instead of a misleading failure.
pub async fn probe_connectivity(form: &EmailAccountForm) -> ProbeReport {
    let google = Arc::new(GoogleCredentialStore::empty());
    let auth = match form_auth_to_runtime(&form.auth) {
        Ok(a) => a,
        Err(e) => {
            let msg = format!("skipped — {e}");
            return ProbeReport {
                imap: Err(msg.clone()),
                smtp: Err(msg),
                spf_dkim_warns: None,
            };
        }
    };
    let account = EmailAccount {
        instance: form.instance.clone(),
        address: form.address.clone(),
        auth,
        allow_agents: vec![],
    };
    let imap_endpoint = ImapEndpoint {
        host: form.imap_host.clone(),
        port: form.imap_port,
        tls: form.imap_tls,
    };
    let smtp_endpoint = SmtpEndpoint {
        host: form.smtp_host.clone(),
        port: form.smtp_port,
        tls: form.smtp_tls,
    };

    let imap = match ImapConnection::connect(&imap_endpoint, &account, google.clone()).await {
        Ok(conn) => {
            let _ = conn.logout().await;
            Ok(format!(
                "{}:{} login OK",
                imap_endpoint.host, imap_endpoint.port
            ))
        }
        Err(e) => Err(format!("{e:#}")),
    };

    let smtp = match SmtpClient::build(&smtp_endpoint, &account, google.clone()).await {
        Ok(client) => match client.test_connection().await {
            Ok(true) => Ok(format!(
                "{}:{} reachable",
                smtp_endpoint.host, smtp_endpoint.port
            )),
            Ok(false) => Err(format!(
                "{}:{} test_connection returned false",
                smtp_endpoint.host, smtp_endpoint.port
            )),
            Err(e) => Err(format!("test_connection: {e:#}")),
        },
        Err(e) => Err(format!("{e:#}")),
    };

    // SPF/DKIM probe — sender domain (the part after `@`) plus the
    // configured SMTP host so the alignment check can flag when the
    // host isn't authorised by the domain's SPF record.
    let domain = form.address.split_once('@').map(|(_, d)| d).unwrap_or("");
    let spf_dkim_warns = if domain.is_empty() {
        None
    } else {
        let report = check_alignment(
            domain,
            Some(&smtp_endpoint.host),
            std::time::Duration::from_secs(5),
        )
        .await;
        if report.dns_error {
            None
        } else {
            Some(
                decide_warns(&report)
                    .iter()
                    .map(|s| (*s).to_string())
                    .collect(),
            )
        }
    };

    ProbeReport {
        imap,
        smtp,
        spf_dkim_warns,
    }
}

/// Map the wizard-local `AuthForm` to the runtime `EmailAuth`.
/// `Oauth2Google` is rejected with a friendly message because the
/// probe path can't resolve the Google access token without a fully
/// initialised `GoogleCredentialStore` (which lives in the daemon,
/// not in `nexo setup`).
fn form_auth_to_runtime(auth: &AuthForm) -> Result<EmailAuth> {
    match auth {
        AuthForm::Password { username, password } => Ok(EmailAuth::Password {
            username: username.clone(),
            password: SecretString::new(password.clone()),
        }),
        AuthForm::Oauth2Static {
            username,
            access_token,
        } => Ok(EmailAuth::OAuth2Static {
            username: username.clone(),
            access_token: SecretString::new(access_token.clone()),
            refresh_token: None,
            expires_at: None,
        }),
        AuthForm::Oauth2Google { .. } => Err(anyhow!(
            "OAuth2 Google probe needs a live google store; the daemon will probe at boot",
        )),
    }
}

/// Single-shot Add or Edit flow. `prefill` populates defaults from
/// an existing account so Edit doesn't force the operator to
/// retype everything; pass `None` for a fresh Add.
fn run_add_or_edit_account(
    config_dir: &Path,
    secrets_dir: &Path,
    prefill: Option<&AccountSummary>,
) -> Result<(PathBuf, PathBuf)> {
    let theme = ColorfulTheme::default();

    let address: String = Input::with_theme(&theme)
        .with_prompt("Email address (e.g. ops@example.com)")
        .with_initial_text(prefill.map(|p| p.address.as_str()).unwrap_or(""))
        .interact_text()?;
    let address = address.trim().to_string();
    if !is_valid_address(&address) {
        return Err(anyhow!("address must look like 'local@domain.tld'"));
    }

    let default_instance = prefill
        .map(|p| p.instance.clone())
        .unwrap_or_else(|| derive_default_instance(&address));
    let instance: String = Input::with_theme(&theme)
        .with_prompt("Instance id (used in `plugin.inbound.email.<instance>`)")
        .default(default_instance)
        .interact_text()?;
    let instance = instance.trim().to_string();
    if instance.is_empty() {
        return Err(anyhow!("instance id cannot be empty"));
    }

    let domain = address.split_once('@').map(|(_, d)| d).unwrap_or("");
    let hint = provider_hint(domain);
    println!(
        "\nDetected provider: {:?} ({}:{} / {}:{})",
        hint.provider, hint.imap_host, hint.imap_port, hint.smtp_host, hint.smtp_port,
    );
    let accept_preset = Confirm::with_theme(&theme)
        .with_prompt("Use the detected preset?")
        .default(true)
        .interact()?;
    let (imap_host, imap_port, imap_tls, smtp_host, smtp_port, smtp_tls) = if accept_preset {
        (
            hint.imap_host.clone(),
            hint.imap_port,
            hint.imap_tls,
            hint.smtp_host.clone(),
            hint.smtp_port,
            hint.smtp_tls,
        )
    } else {
        let imap_host: String = Input::with_theme(&theme)
            .with_prompt("IMAP host")
            .default(hint.imap_host.clone())
            .interact_text()?;
        let imap_port: u16 = Input::with_theme(&theme)
            .with_prompt("IMAP port")
            .default(hint.imap_port)
            .interact_text()?;
        let smtp_host: String = Input::with_theme(&theme)
            .with_prompt("SMTP host")
            .default(hint.smtp_host.clone())
            .interact_text()?;
        let smtp_port: u16 = Input::with_theme(&theme)
            .with_prompt("SMTP port")
            .default(hint.smtp_port)
            .interact_text()?;
        (
            imap_host,
            imap_port,
            hint.imap_tls,
            smtp_host,
            smtp_port,
            hint.smtp_tls,
        )
    };

    // Plain TLS guard — silently storing creds for a server that
    // exchanges them in cleartext is a security trap; require an
    // explicit opt-in before continuing.
    if matches!(imap_tls, TlsMode::Plain) || matches!(smtp_tls, TlsMode::Plain) {
        println!(
            "\n⚠  Plain TLS chosen for {}. Credentials will travel in cleartext over the network.",
            plain_tls_legs(&imap_tls, &smtp_tls),
        );
        if !Confirm::with_theme(&theme)
            .with_prompt("Confirm: I understand and want to continue with PLAIN TLS")
            .default(false)
            .interact()?
        {
            return Err(anyhow!("aborted by operator (plain TLS rejected)"));
        }
    }

    let auth_idx = Select::with_theme(&theme)
        .with_prompt("Auth kind")
        .items(auth_kind_choices())
        .default(if hint.suggest_oauth_google { 2 } else { 0 })
        .interact()?;
    if auth_idx == 0 && password_likely_to_fail(&hint.provider) {
        println!(
            "\n⚠  {:?} typically rejects raw account passwords. Use an app-password (gmail / outlook → 'app password' in account settings) or switch to OAuth2.",
            hint.provider,
        );
        if !Confirm::with_theme(&theme)
            .with_prompt("Continue with Password anyway?")
            .default(false)
            .interact()?
        {
            return Err(anyhow!(
                "aborted by operator (password rejected for managed provider)"
            ));
        }
    }
    let auth = match auth_idx {
        0 => {
            let username: String = Input::with_theme(&theme)
                .with_prompt("Username")
                .default(address.clone())
                .interact_text()?;
            let password = Password::with_theme(&theme)
                .with_prompt("Password / app password")
                .with_confirmation("Confirm password", "Passwords do not match")
                .interact()?;
            AuthForm::Password { username, password }
        }
        1 => {
            let username: String = Input::with_theme(&theme)
                .with_prompt("Username")
                .default(address.clone())
                .interact_text()?;
            let access_token = Password::with_theme(&theme)
                .with_prompt("OAuth2 access token")
                .interact()?;
            AuthForm::Oauth2Static {
                username,
                access_token,
            }
        }
        _ => {
            let username: String = Input::with_theme(&theme)
                .with_prompt("Username")
                .default(address.clone())
                .interact_text()?;
            let google_account_id = pick_or_prompt_google_account_id(config_dir, &theme)?;
            AuthForm::Oauth2Google {
                username,
                google_account_id,
            }
        }
    };

    let form = EmailAccountForm {
        instance,
        address,
        provider: hint.provider,
        imap_host,
        imap_port,
        imap_tls,
        smtp_host,
        smtp_port,
        smtp_tls,
        auth,
    };

    println!("\nReview:");
    println!("{}", render_review(&form));
    if !Confirm::with_theme(&theme)
        .with_prompt("Probe IMAP + SMTP before saving?")
        .default(true)
        .interact()?
    {
        // Operator declined probe — still ask for a final confirm
        // before persisting.
    } else {
        println!("Probing… (this can take up to 30s)");
        let rt = tokio::runtime::Builder::new_multi_thread()
            .enable_all()
            .build()
            .context("build tokio runtime for connectivity probe")?;
        let report = rt.block_on(probe_connectivity(&form));
        match &report.imap {
            Ok(s) => println!("  ✔ IMAP {s}"),
            Err(e) => println!("  ✘ IMAP {e}"),
        }
        match &report.smtp {
            Ok(s) => println!("  ✔ SMTP {s}"),
            Err(e) => println!("  ✘ SMTP {e}"),
        }
        match &report.spf_dkim_warns {
            None => println!("  ⊘ SPF/DKIM probe skipped (DNS error or empty domain)"),
            Some(v) if v.is_empty() => println!("  ✔ SPF/DKIM aligned for sender domain"),
            Some(warns) => {
                println!("  ⚠  SPF/DKIM warnings:");
                for w in warns {
                    println!("       - {w}");
                }
            }
        }
        if !report.ok()
            && !Confirm::with_theme(&theme)
                .with_prompt("Probe failed. Save anyway?")
                .default(false)
                .interact()?
        {
            return Err(anyhow!("aborted by operator after failed probe"));
        }
    }

    if !Confirm::with_theme(&theme)
        .with_prompt("Persist YAML + secret TOML?")
        .default(true)
        .interact()?
    {
        return Err(anyhow!("aborted by operator before persist"));
    }

    let yaml_path = upsert_email_account_yaml(config_dir, &form)?;
    let toml_path = write_secret_toml(secrets_dir, &form.instance, &serialise_secret_toml(&form))?;
    println!("\n✔ wrote {}", yaml_path.display());
    println!("✔ wrote {} (mode 0o600)", toml_path.display());
    println!(
        "ℹ  if the daemon is running it will hot-reload via the config file watcher; \
         otherwise the next `nexo run` picks up the change."
    );
    Ok((yaml_path, toml_path))
}

/// Email setup menu — list / add / edit / delete / probe / quit.
/// Loops until the operator picks "Salir". Each action is
/// independent and any error inside a single action is surfaced
/// (with a friendly print) without aborting the loop, so a
/// mis-typed password on Add doesn't block the operator from
/// reaching Delete.
pub fn run_email_wizard(config_dir: &Path, secrets_dir: &Path) -> Result<()> {
    let theme = ColorfulTheme::default();
    println!("\nEmail setup");
    println!("-----------");
    loop {
        let actions = [
            "Listar cuentas",
            "Agregar cuenta",
            "Editar cuenta",
            "Eliminar cuenta",
            "Probar conectividad",
            "Salir",
        ];
        let pick = Select::with_theme(&theme)
            .with_prompt("¿Qué querés hacer?")
            .items(&actions)
            .default(0)
            .interact()?;
        let outcome: Result<()> = match pick {
            0 => action_list(config_dir, secrets_dir),
            1 => action_add(config_dir, secrets_dir),
            2 => action_edit(config_dir, secrets_dir),
            3 => action_delete(config_dir, secrets_dir),
            4 => action_probe(config_dir, secrets_dir),
            _ => return Ok(()),
        };
        if let Err(e) = outcome {
            eprintln!("⚠  {e:#}");
        }
        println!();
    }
}

fn action_list(config_dir: &Path, secrets_dir: &Path) -> Result<()> {
    let accounts = list_accounts(config_dir, secrets_dir)?;
    if accounts.is_empty() {
        println!("(sin cuentas configuradas)");
        return Ok(());
    }
    println!("{} cuentas configuradas:", accounts.len());
    for a in &accounts {
        let secret_marker = if a.has_secret_toml {
            "✔"
        } else {
            "✘ falta secret"
        };
        println!(
            "  • {:<16} {:<32} provider={} imap={} smtp={} {}",
            a.instance, a.address, a.provider, a.imap_host, a.smtp_host, secret_marker,
        );
    }
    Ok(())
}

fn action_add(config_dir: &Path, secrets_dir: &Path) -> Result<()> {
    run_add_or_edit_account(config_dir, secrets_dir, None).map(|_| ())
}

fn action_edit(config_dir: &Path, secrets_dir: &Path) -> Result<()> {
    let accounts = list_accounts(config_dir, secrets_dir)?;
    if accounts.is_empty() {
        return Err(anyhow!(
            "no hay cuentas configuradas — usá 'Agregar cuenta'"
        ));
    }
    let labels: Vec<String> = accounts
        .iter()
        .map(|a| format!("{} ({})", a.instance, a.address))
        .collect();
    let theme = ColorfulTheme::default();
    let idx = Select::with_theme(&theme)
        .with_prompt("Cuenta a editar")
        .items(&labels)
        .default(0)
        .interact()?;
    run_add_or_edit_account(config_dir, secrets_dir, Some(&accounts[idx])).map(|_| ())
}

fn action_delete(config_dir: &Path, secrets_dir: &Path) -> Result<()> {
    let accounts = list_accounts(config_dir, secrets_dir)?;
    if accounts.is_empty() {
        return Err(anyhow!("no hay cuentas configuradas — nada para borrar"));
    }
    let labels: Vec<String> = accounts
        .iter()
        .map(|a| format!("{} ({})", a.instance, a.address))
        .collect();
    let theme = ColorfulTheme::default();
    let idx = Select::with_theme(&theme)
        .with_prompt("Cuenta a eliminar")
        .items(&labels)
        .default(0)
        .interact()?;
    let target = &accounts[idx];
    if !Confirm::with_theme(&theme)
        .with_prompt(format!(
            "¿Borrar '{}' ({}) y su secret TOML?",
            target.instance, target.address
        ))
        .default(false)
        .interact()?
    {
        return Err(anyhow!("cancelado"));
    }
    delete_account(config_dir, secrets_dir, &target.instance)?;
    println!("✔ '{}' eliminado.", target.instance);
    Ok(())
}

fn action_probe(_config_dir: &Path, _secrets_dir: &Path) -> Result<()> {
    // Probe-without-persist: run the same prompts as Add but don't
    // call upsert/write_secret. Useful for "do my creds work?"
    // before committing to email.yaml.
    println!("(probe sin guardar — pedí los mismos campos que en 'Agregar', sin persistir)");
    let theme = ColorfulTheme::default();
    let address: String = Input::with_theme(&theme)
        .with_prompt("Email address")
        .interact_text()?;
    let address = address.trim().to_string();
    if !is_valid_address(&address) {
        return Err(anyhow!("address must look like 'local@domain.tld'"));
    }
    let domain = address.split_once('@').map(|(_, d)| d).unwrap_or("");
    let hint = provider_hint(domain);
    let auth_idx = Select::with_theme(&theme)
        .with_prompt("Auth kind")
        .items(auth_kind_choices())
        .default(if hint.suggest_oauth_google { 2 } else { 0 })
        .interact()?;
    let auth = match auth_idx {
        0 => {
            let username: String = Input::with_theme(&theme)
                .with_prompt("Username")
                .default(address.clone())
                .interact_text()?;
            let password = Password::with_theme(&theme)
                .with_prompt("Password / app password")
                .interact()?;
            AuthForm::Password { username, password }
        }
        1 => {
            let username: String = Input::with_theme(&theme)
                .with_prompt("Username")
                .default(address.clone())
                .interact_text()?;
            let access_token = Password::with_theme(&theme)
                .with_prompt("OAuth2 access token")
                .interact()?;
            AuthForm::Oauth2Static {
                username,
                access_token,
            }
        }
        _ => {
            let username: String = Input::with_theme(&theme)
                .with_prompt("Username")
                .default(address.clone())
                .interact_text()?;
            AuthForm::Oauth2Google {
                username,
                google_account_id: String::new(),
            }
        }
    };
    let form = EmailAccountForm {
        instance: derive_default_instance(&address),
        address,
        provider: hint.provider,
        imap_host: hint.imap_host.clone(),
        imap_port: hint.imap_port,
        imap_tls: hint.imap_tls,
        smtp_host: hint.smtp_host.clone(),
        smtp_port: hint.smtp_port,
        smtp_tls: hint.smtp_tls,
        auth,
    };
    let rt = tokio::runtime::Builder::new_multi_thread()
        .enable_all()
        .build()
        .context("build tokio runtime for connectivity probe")?;
    let report = rt.block_on(probe_connectivity(&form));
    match &report.imap {
        Ok(s) => println!("  ✔ IMAP {s}"),
        Err(e) => println!("  ✘ IMAP {e}"),
    }
    match &report.smtp {
        Ok(s) => println!("  ✔ SMTP {s}"),
        Err(e) => println!("  ✘ SMTP {e}"),
    }
    match &report.spf_dkim_warns {
        None => println!("  ⊘ SPF/DKIM probe skipped (DNS error or empty domain)"),
        Some(v) if v.is_empty() => println!("  ✔ SPF/DKIM aligned for sender domain"),
        Some(warns) => {
            println!("  ⚠  SPF/DKIM warnings:");
            for w in warns {
                println!("       - {w}");
            }
        }
    }
    Ok(())
}

/// Surface a `Select` of `id`s from `google-auth.yaml`. Falls back to
/// a free-text `Input` when the file is missing / empty / unparseable
/// so a brand-new operator (no Google accounts wired yet) can still
/// type the id they intend to add later. Adds a "(other — type
/// manually)" sentinel as the last item so the operator can override
/// even when accounts exist.
fn pick_or_prompt_google_account_id(config_dir: &Path, theme: &ColorfulTheme) -> Result<String> {
    let ids = list_google_account_ids(config_dir);
    if ids.is_empty() {
        let s: String = Input::with_theme(theme)
            .with_prompt("Google account id (from google-auth.yaml)")
            .interact_text()?;
        return Ok(s.trim().to_string());
    }
    let mut labels: Vec<String> = ids.iter().map(|s| s.to_string()).collect();
    labels.push("(otra — escribir a mano)".into());
    let idx = Select::with_theme(theme)
        .with_prompt("Google account")
        .items(&labels)
        .default(0)
        .interact()?;
    if idx == labels.len() - 1 {
        let s: String = Input::with_theme(theme)
            .with_prompt("Google account id")
            .interact_text()?;
        Ok(s.trim().to_string())
    } else {
        Ok(ids[idx].clone())
    }
}

/// Render the comma-separated list of legs that ended up on plain
/// TLS. Used by the warning banner so the operator knows whether
/// the IMAP, SMTP, or both connections are plaintext.
fn plain_tls_legs(imap: &TlsMode, smtp: &TlsMode) -> String {
    let mut legs = Vec::with_capacity(2);
    if matches!(imap, TlsMode::Plain) {
        legs.push("IMAP");
    }
    if matches!(smtp, TlsMode::Plain) {
        legs.push("SMTP");
    }
    legs.join(" + ")
}

/// True for providers known to refuse raw account passwords on
/// IMAP/SMTP (Gmail / Outlook). Yahoo + iCloud accept app-passwords
/// too but allow IMAP/SMTP with the regular password when the user
/// hasn't enrolled 2FA — the warn would be noisy. Custom is opaque
/// and never warned.
fn password_likely_to_fail(provider: &EmailProvider) -> bool {
    matches!(provider, EmailProvider::Gmail | EmailProvider::Outlook)
}

fn is_valid_address(addr: &str) -> bool {
    // Cheap syntactic check — full RFC 5322 is overkill for a CLI
    // wizard. Require: exactly one '@', non-empty local + domain,
    // domain has at least one dot, no whitespace.
    if addr.chars().any(|c| c.is_whitespace()) {
        return false;
    }
    let mut parts = addr.split('@');
    let local = match parts.next() {
        Some(s) if !s.is_empty() => s,
        _ => return false,
    };
    let domain = match parts.next() {
        Some(s) if !s.is_empty() => s,
        _ => return false,
    };
    if parts.next().is_some() {
        return false;
    }
    if !domain.contains('.') {
        return false;
    }
    !local.is_empty()
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    fn form(instance: &str, address: &str) -> EmailAccountForm {
        EmailAccountForm {
            instance: instance.into(),
            address: address.into(),
            provider: EmailProvider::Custom,
            imap_host: "imap.example.com".into(),
            imap_port: 993,
            imap_tls: TlsMode::ImplicitTls,
            smtp_host: "smtp.example.com".into(),
            smtp_port: 587,
            smtp_tls: TlsMode::Starttls,
            auth: AuthForm::Password {
                username: address.into(),
                password: "hunter2".into(),
            },
        }
    }

    #[test]
    fn derive_default_instance_pulls_localpart() {
        assert_eq!(derive_default_instance("ops@example.com"), "ops");
    }

    #[test]
    fn derive_default_instance_strips_plus_tag() {
        assert_eq!(
            derive_default_instance("Alice.Doe+work@gmail.com"),
            "alice.doe"
        );
    }

    #[test]
    fn derive_default_instance_falls_back_to_ops() {
        assert_eq!(derive_default_instance(""), "ops");
        assert_eq!(derive_default_instance("@x"), "ops");
    }

    #[test]
    fn render_account_block_matches_yaml_shape() {
        let body = render_account_block(&form("ops", "ops@x.com"));
        assert!(body.contains("  - instance: ops\n"));
        assert!(body.contains("    address: ops@x.com\n"));
        assert!(body.contains("    provider: custom\n"));
        assert!(body.contains("imap.example.com"));
        assert!(body.contains("smtp.example.com"));
    }

    #[test]
    fn serialise_secret_toml_password() {
        let s = serialise_secret_toml(&form("ops", "ops@x.com"));
        assert!(s.contains("kind = \"password\""));
        assert!(s.contains("password = \"hunter2\""));
    }

    #[test]
    fn serialise_secret_toml_oauth2_google() {
        let mut f = form("ops", "ops@x.com");
        f.auth = AuthForm::Oauth2Google {
            username: "ops@gmail.com".into(),
            google_account_id: "ops".into(),
        };
        let s = serialise_secret_toml(&f);
        assert!(s.contains("kind = \"oauth2_google\""));
        assert!(s.contains("google_account_id = \"ops\""));
    }

    #[test]
    fn write_secret_toml_atomic_and_chmod() {
        let dir = tempdir().unwrap();
        let path = write_secret_toml(dir.path(), "ops", "[auth]\nkind=\"password\"\n").unwrap();
        assert!(path.ends_with("email/ops.toml"));
        let body = std::fs::read_to_string(&path).unwrap();
        assert!(body.contains("password"));
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mode = std::fs::metadata(&path).unwrap().permissions().mode() & 0o777;
            assert_eq!(mode, 0o600);
        }
    }

    #[test]
    fn upsert_creates_yaml_when_absent() {
        let dir = tempdir().unwrap();
        let path = upsert_email_account_yaml(dir.path(), &form("ops", "ops@x.com")).unwrap();
        let body = std::fs::read_to_string(&path).unwrap();
        assert!(body.contains("ops@x.com"));
        assert!(body.contains("instance: ops"));
    }

    #[test]
    fn upsert_replaces_existing_instance_in_place() {
        let dir = tempdir().unwrap();
        let mut f1 = form("ops", "old@x.com");
        let mut f2 = form("ops", "new@x.com");
        f2.imap_host = "imap.new.com".into();
        f1.imap_host = "imap.old.com".into();
        upsert_email_account_yaml(dir.path(), &f1).unwrap();
        let path = upsert_email_account_yaml(dir.path(), &f2).unwrap();
        let body = std::fs::read_to_string(&path).unwrap();
        assert!(body.contains("new@x.com"));
        assert!(!body.contains("old@x.com"));
        assert!(body.contains("imap.new.com"));
    }

    #[test]
    fn upsert_appends_new_instance_alongside_existing() {
        let dir = tempdir().unwrap();
        upsert_email_account_yaml(dir.path(), &form("ops", "ops@x.com")).unwrap();
        let path =
            upsert_email_account_yaml(dir.path(), &form("support", "support@x.com")).unwrap();
        let body = std::fs::read_to_string(&path).unwrap();
        assert!(body.contains("ops@x.com"));
        assert!(body.contains("support@x.com"));
    }

    #[test]
    fn list_accounts_empty_when_yaml_missing() {
        let dir = tempdir().unwrap();
        let out = list_accounts(dir.path(), dir.path()).unwrap();
        assert!(out.is_empty());
    }

    #[test]
    fn list_accounts_returns_summaries() {
        let cfg = tempdir().unwrap();
        let sec = tempdir().unwrap();
        upsert_email_account_yaml(cfg.path(), &form("ops", "ops@x.com")).unwrap();
        upsert_email_account_yaml(cfg.path(), &form("support", "support@x.com")).unwrap();
        // Only `ops` has a secret on disk.
        write_secret_toml(sec.path(), "ops", "[auth]\nkind=\"password\"\n").unwrap();
        let out = list_accounts(cfg.path(), sec.path()).unwrap();
        assert_eq!(out.len(), 2);
        let ops = out.iter().find(|a| a.instance == "ops").unwrap();
        let sup = out.iter().find(|a| a.instance == "support").unwrap();
        assert_eq!(ops.address, "ops@x.com");
        assert!(ops.has_secret_toml);
        assert!(!sup.has_secret_toml);
        assert_eq!(ops.imap_host, "imap.example.com");
    }

    #[test]
    fn delete_account_removes_yaml_block_and_secret() {
        let cfg = tempdir().unwrap();
        let sec = tempdir().unwrap();
        upsert_email_account_yaml(cfg.path(), &form("ops", "ops@x.com")).unwrap();
        upsert_email_account_yaml(cfg.path(), &form("support", "support@x.com")).unwrap();
        write_secret_toml(sec.path(), "ops", "[auth]\nkind=\"password\"\n").unwrap();
        delete_account(cfg.path(), sec.path(), "ops").unwrap();
        let body = std::fs::read_to_string(cfg.path().join("plugins").join("email.yaml")).unwrap();
        assert!(!body.contains("ops@x.com"));
        assert!(body.contains("support@x.com"));
        assert!(!sec.path().join("email").join("ops.toml").exists());
    }

    #[test]
    fn delete_account_idempotent_on_missing_secret() {
        let cfg = tempdir().unwrap();
        let sec = tempdir().unwrap();
        upsert_email_account_yaml(cfg.path(), &form("ops", "ops@x.com")).unwrap();
        // No write_secret_toml → secret never landed on disk.
        delete_account(cfg.path(), sec.path(), "ops").unwrap();
        let body = std::fs::read_to_string(cfg.path().join("plugins").join("email.yaml")).unwrap();
        assert!(!body.contains("ops@x.com"));
    }

    #[test]
    fn delete_account_errors_on_unknown_instance() {
        let cfg = tempdir().unwrap();
        let sec = tempdir().unwrap();
        upsert_email_account_yaml(cfg.path(), &form("ops", "ops@x.com")).unwrap();
        let err = delete_account(cfg.path(), sec.path(), "nope").unwrap_err();
        assert!(format!("{err:#}").contains("nope"));
    }

    #[test]
    fn render_review_includes_each_field_and_redacts_secret() {
        let f = form("ops", "ops@x.com");
        let s = render_review(&f);
        assert!(s.contains("ops@x.com"));
        assert!(s.contains("imap.example.com:993"));
        assert!(s.contains("smtp.example.com:587"));
        assert!(s.contains("password"));
        assert!(s.contains("<hidden>"));
        // The plaintext password from the form must NOT appear in
        // the review screen — operators can be screen-recorded.
        assert!(!s.contains("hunter2"));
    }

    #[test]
    fn is_valid_address_accepts_normal_form() {
        assert!(is_valid_address("ops@example.com"));
        assert!(is_valid_address("a.b+c@sub.example.co.uk"));
    }

    #[test]
    fn is_valid_address_rejects_pathological() {
        assert!(!is_valid_address(""));
        assert!(!is_valid_address("nodomain@"));
        assert!(!is_valid_address("@nodomain"));
        assert!(!is_valid_address("a@b")); // no TLD dot
        assert!(!is_valid_address("a@@b.c"));
        assert!(!is_valid_address("a b@c.d"));
    }

    #[test]
    fn form_auth_to_runtime_password_round_trips_username() {
        let f = AuthForm::Password {
            username: "ops@x.com".into(),
            password: "hunter2".into(),
        };
        let runtime = form_auth_to_runtime(&f).unwrap();
        match runtime {
            EmailAuth::Password { username, .. } => assert_eq!(username, "ops@x.com"),
            _ => panic!("expected Password variant"),
        }
    }

    #[test]
    fn plain_tls_legs_renders_each_leg() {
        assert_eq!(
            plain_tls_legs(&TlsMode::Plain, &TlsMode::ImplicitTls),
            "IMAP"
        );
        assert_eq!(
            plain_tls_legs(&TlsMode::ImplicitTls, &TlsMode::Plain),
            "SMTP"
        );
        assert_eq!(
            plain_tls_legs(&TlsMode::Plain, &TlsMode::Plain),
            "IMAP + SMTP"
        );
        assert_eq!(plain_tls_legs(&TlsMode::Starttls, &TlsMode::Starttls), "");
    }

    #[test]
    fn password_likely_to_fail_only_for_managed_providers() {
        assert!(password_likely_to_fail(&EmailProvider::Gmail));
        assert!(password_likely_to_fail(&EmailProvider::Outlook));
        assert!(!password_likely_to_fail(&EmailProvider::Yahoo));
        assert!(!password_likely_to_fail(&EmailProvider::Icloud));
        assert!(!password_likely_to_fail(&EmailProvider::Custom));
    }

    #[test]
    fn list_google_account_ids_empty_when_file_missing() {
        let dir = tempdir().unwrap();
        assert!(list_google_account_ids(dir.path()).is_empty());
    }

    #[test]
    fn list_google_account_ids_returns_ids_when_present() {
        let dir = tempdir().unwrap();
        let plugins = dir.path().join("plugins");
        std::fs::create_dir_all(&plugins).unwrap();
        std::fs::write(
            plugins.join("google-auth.yaml"),
            r#"google_auth:
  accounts:
    - id: ana@x.com
      agent_id: ana
      client_id_path: /tmp/c
      client_secret_path: /tmp/s
      token_path: /tmp/t
    - id: bob@x.com
      agent_id: bob
      client_id_path: /tmp/c2
      client_secret_path: /tmp/s2
      token_path: /tmp/t2
"#,
        )
        .unwrap();
        let ids = list_google_account_ids(dir.path());
        assert_eq!(ids, vec!["ana@x.com".to_string(), "bob@x.com".to_string()]);
    }

    #[test]
    fn list_google_account_ids_tolerates_malformed_yaml() {
        let dir = tempdir().unwrap();
        let plugins = dir.path().join("plugins");
        std::fs::create_dir_all(&plugins).unwrap();
        std::fs::write(plugins.join("google-auth.yaml"), "this: [is: bad").unwrap();
        // Malformed file → empty vec, never panics.
        assert!(list_google_account_ids(dir.path()).is_empty());
    }

    #[test]
    fn form_auth_to_runtime_oauth2_google_skipped() {
        let f = AuthForm::Oauth2Google {
            username: "ops@x.com".into(),
            google_account_id: "ops".into(),
        };
        let err = form_auth_to_runtime(&f).unwrap_err();
        assert!(format!("{err:#}").contains("google"));
    }
}
